export let ayurvedicMedicines = [
  {
    id: 1,
    img: "https://images.pexels.com/photos/4041392/pexels-photo-4041392.jpeg?auto=compress&cs=tinysrgb&w=400",
    productName: "Radhey Pure Desi Ghee",
    category: "Siddhar",
    brand: "Kottakkal",
    type: "General",
    ailments: ["Digestion", "Immunity"],
    productDescription: "100% pure & natural ghee made from Indian Native Gir cow's milk. Free from artificial colours, preservatives, flavours, sweeteners and chemicals.",
    price: 199,
    originalPrice: 249,
    onSale: true,
    rating: 4,
    reviews: 107,
  },
  {
    id: 2,
    img: "https://images.pexels.com/photos/4041392/pexels-photo-4041392.jpeg?auto=compress&cs=tinysrgb&w=400",
    productName: "Ashwagandha Root Churnam",
    category: "Classical Medicines",
    brand: "AVP Ayurveda",
    type: "Churnam",
    ailments: ["Stress", "Immunity"],
    productDescription: "Traditional Ashwagandha root powder for strength, vitality and stress relief. Sourced from certified organic farms.",
    price: 250,
    originalPrice: null,
    onSale: false,
    rating: 5,
    reviews: 91,
  },
  {
    id: 3,
    img: "https://images.pexels.com/photos/3735747/pexels-photo-3735747.jpeg?auto=compress&cs=tinysrgb&w=400",
    productName: "Neem Herbal Face Wash",
    category: "Personal Care",
    brand: "Kerala Ayurveda",
    type: "General",
    ailments: ["Skin"],
    productDescription: "Gentle neem-based herbal face wash that deeply cleanses, fights acne and brightens skin. Suitable for all skin types.",
    price: 149,
    originalPrice: 199,
    onSale: true,
    rating: 4,
    reviews: 40,
  },
  {
    id: 4,
    img: "https://images.pexels.com/photos/5938244/pexels-photo-5938244.jpeg?auto=compress&cs=tinysrgb&w=400",
    productName: "Himalaya Liv.52 DS Tablet",
    category: "Brands",
    brand: "AVN",
    type: "Capsules",
    ailments: ["Digestion", "Liver"],
    productDescription: "Himalaya Liv.52 DS supports liver health and promotes detoxification. Trusted by doctors for decades.",
    price: 185,
    originalPrice: null,
    onSale: false,
    rating: 5,
    reviews: 203,
  },
  {
    id: 5,
    img: "https://images.pexels.com/photos/8329969/pexels-photo-8329969.jpeg?auto=compress&cs=tinysrgb&w=400",
    productName: "Chyawanprash Immunity Jam",
    category: "Health & Nutrition",
    brand: "Vaidyaratnam",
    type: "General",
    ailments: ["Immunity", "Cold"],
    productDescription: "Ancient Ayurvedic formulation with 40+ herbs for boosting immunity, energy and overall vitality.",
    price: 399,
    originalPrice: 499,
    onSale: true,
    rating: 5,
    reviews: 310,
  },
  {
    id: 6,
    img: "https://images.pexels.com/photos/4041001/pexels-photo-4041001.jpeg?auto=compress&cs=tinysrgb&w=400",
    productName: "Triphala Churna",
    category: "General",
    brand: "Kottakkal",
    type: "Churnam",
    ailments: ["Digestion", "Constipation"],
    productDescription: "Classic three-fruit formula combining Amalaki, Bibhitaki and Haritaki for digestive health and detox.",
    price: 120,
    originalPrice: null,
    onSale: false,
    rating: 4,
    reviews: 88,
  },
  {
    id: 7,
    img: "https://images.pexels.com/photos/5699516/pexels-photo-5699516.jpeg?auto=compress&cs=tinysrgb&w=400",
    productName: "Tulsi Immunity Drops",
    category: "Siddhar",
    brand: "AVP Ayurveda",
    type: "Tailam",
    ailments: ["Cold", "Immunity"],
    productDescription: "Pure Tulsi (Holy Basil) drops for immunity, respiratory health and stress relief. 100% natural and preservative-free.",
    price: 150,
    originalPrice: null,
    onSale: false,
    rating: 4,
    reviews: 55,
  },
  {
    id: 8,
    img: "https://images.pexels.com/photos/4041392/pexels-photo-4041392.jpeg?auto=compress&cs=tinysrgb&w=400",
    productName: "Saraswatarishtam Syrup",
    category: "Classical Medicines",
    brand: "Kottakkal",
    type: "Leham",
    ailments: ["Memory", "Stress"],
    productDescription: "Classical Ayurvedic tonic for memory, concentration, and cognitive health. Ideal for students and professionals.",
    price: 320,
    originalPrice: 380,
    onSale: true,
    rating: 5,
    reviews: 120,
  },
  {
    id: 9,
    img: "https://images.pexels.com/photos/3735747/pexels-photo-3735747.jpeg?auto=compress&cs=tinysrgb&w=400",
    productName: "Coconut Oil Hair Mask",
    category: "Personal Care",
    brand: "Kerala Ayurveda",
    type: "Tailam",
    ailments: ["Hair"],
    productDescription: "Deep conditioning herbal hair mask with coconut oil, amla and bhringraj for strong, shiny and healthy hair.",
    price: 199,
    originalPrice: null,
    onSale: false,
    rating: 4,
    reviews: 67,
  },
  {
    id: 10,
    img: "https://images.pexels.com/photos/5938244/pexels-photo-5938244.jpeg?auto=compress&cs=tinysrgb&w=400",
    productName: "Dabur Honey Pure Organic",
    category: "Brands",
    brand: "AVN",
    type: "General",
    ailments: ["Immunity", "Cold"],
    productDescription: "100% pure organic honey with natural antioxidants, antimicrobial properties and natural sweetness.",
    price: 299,
    originalPrice: 349,
    onSale: true,
    rating: 4,
    reviews: 145,
  },
  {
    id: 11,
    img: "https://images.pexels.com/photos/8329969/pexels-photo-8329969.jpeg?auto=compress&cs=tinysrgb&w=400",
    productName: "Spirulina Protein Powder",
    category: "Health & Nutrition",
    brand: "Vaidyaratnam",
    type: "Churnam",
    ailments: ["Immunity", "Nutrition"],
    productDescription: "High-protein spirulina powder packed with vitamins, minerals and amino acids for daily nutrition.",
    price: 550,
    originalPrice: null,
    onSale: false,
    rating: 5,
    reviews: 200,
  },
  {
    id: 12,
    img: "https://images.pexels.com/photos/4041001/pexels-photo-4041001.jpeg?auto=compress&cs=tinysrgb&w=400",
    productName: "Amla Neem Giloy Juice",
    category: "General",
    brand: "Kottakkal",
    type: "Leham",
    ailments: ["Immunity", "Digestion", "Diabetes"],
    productDescription: "A powerful combination of Amla, Neem and Giloy for detoxification, immunity and skin health.",
    price: 180,
    originalPrice: 220,
    onSale: true,
    rating: 4,
    reviews: 88,
  },
  {
    id: 13,
    img: "https://images.pexels.com/photos/5699516/pexels-photo-5699516.jpeg?auto=compress&cs=tinysrgb&w=400",
    productName: "Nilibhringadi Kera Tailam",
    category: "Siddhar",
    brand: "Kottakkal",
    type: "Tailam",
    ailments: ["Hair"],
    productDescription: "Classical Ayurvedic hair oil with Nili, Bhringraj, Amla and Yashtimadhu in pure coconut oil base. Prevents hairfall and premature greying.",
    price: 275,
    originalPrice: null,
    onSale: false,
    rating: 4,
    reviews: 91,
  },
  {
    id: 14,
    img: "https://images.pexels.com/photos/4041392/pexels-photo-4041392.jpeg?auto=compress&cs=tinysrgb&w=400",
    productName: "Dasamularishtam",
    category: "Classical Medicines",
    brand: "AVP Ayurveda",
    type: "Leham",
    ailments: ["Cold", "Digestion"],
    productDescription: "Classical Ayurvedic formulation with ten roots for respiratory health, digestive strength and post-natal recovery.",
    price: 130,
    originalPrice: null,
    onSale: false,
    rating: 3,
    reviews: 40,
  },
  {
    id: 15,
    img: "https://images.pexels.com/photos/3735747/pexels-photo-3735747.jpeg?auto=compress&cs=tinysrgb&w=400",
    productName: "Kumkumadi Brightening Oil",
    category: "Personal Care",
    brand: "Kerala Ayurveda",
    type: "Tailam",
    ailments: ["Skin"],
    productDescription: "Luxurious Kumkumadi face oil with saffron, sandalwood and rose for radiant, glowing and even-toned skin.",
    price: 450,
    originalPrice: 550,
    onSale: true,
    rating: 5,
    reviews: 176,
  },
];