import React, { createContext, useContext, useState } from 'react';

const translations = {
  en: {
    home: 'HOME',
    aboutUs: 'ABOUT US',
    siddhar: 'SIDDHAR',
    collections: 'COLLECTIONS',
    wishlist: 'WISHLIST',
    login: 'LOGIN',
    createAccount: 'CREATE AN ACCOUNT',
    cart: 'CART',
    yourCart: 'Your Cart',
    emptyCart: 'Your cart is empty.',
    product: 'PRODUCT',
    price: 'PRICE',
    quantity: 'QUANTITY',
    total: 'TOTAL',
    subtotal: 'Subtotal',
    proceedCheckout: 'Proceed to Checkout',
    continueShopping: 'Continue Shopping',
    remove: 'Remove',
    checkout: 'Checkout',
    shippingInfo: 'Shipping Information',
    firstName: 'First Name',
    lastName: 'Last Name',
    email: 'Email Address',
    phone: 'Phone Number',
    address: 'Address',
    city: 'City',
    state: 'State',
    pincode: 'Pincode',
    orderSummary: 'Order Summary',
    placeOrder: 'Place Order',
    payment: 'Payment',
    selectPayment: 'Select Payment Method',
    upi: 'UPI',
    card: 'Credit / Debit Card',
    cod: 'Cash on Delivery',
    payNow: 'Pay Now',
    orderSuccess: 'Payment Successful!',
    orderSuccessMsg: 'Your order has been placed. Thank you!',
    backHome: 'Back to Home',
    yourWishlist: 'Your Wishlist',
    emptyWishlist: 'Your wishlist is empty.',
    addToCart: 'ADD TO CART',
    addedToCart: 'Added to Cart!',
    addedToWishlist: 'Added to Wishlist!',
    removeWishlist: 'Remove',
    reviews: 'reviews',
    availability: 'Availability',
    available: 'Available',
    profile: 'Profile',
    freeShipping: 'FREE Shipping',
    onOrderAbove: 'ON ORDER ABOVE ₹900',
    searchPlaceholder: 'Search',
    shipping: 'Shipping',
    free: 'FREE',
    grandTotal: 'Grand Total',
    upiId: 'Enter UPI ID (e.g. name@upi)',
    cardNumber: 'Card Number',
    expiry: 'Expiry (MM/YY)',
    cvv: 'CVV',
    upiVerify: 'Verify & Pay',
    orderPlaced: 'Order Placed Successfully!',
    thankYou: 'Thank you for shopping with us.',
    orderId: 'Order ID',
    topSelling: 'Top Selling Ayurvedic Medicines',
    exploreMore: 'Explore our best rated Online Ayurvedic Medicines',
    naturalHealthcare: 'Natural healthcare with Ayurveda',
    bundle: 'Bundle',
  },
  ta: {
    home: 'முகப்பு',
    aboutUs: 'எங்களை பற்றி',
    siddhar: 'சித்தர்',
    collections: 'தொகுப்புகள்',
    wishlist: 'விருப்பப் பட்டியல்',
    login: 'உள்நுழைவு',
    createAccount: 'கணக்கு உருவாக்கு',
    cart: 'வண்டி',
    yourCart: 'உங்கள் வண்டி',
    emptyCart: 'உங்கள் வண்டி காலியாக உள்ளது.',
    product: 'பொருள்',
    price: 'விலை',
    quantity: 'அளவு',
    total: 'மொத்தம்',
    subtotal: 'இடைத்தொகை',
    proceedCheckout: 'வாங்குவதற்கு தொடர்க',
    continueShopping: 'தொடர்ந்து ஷாப்பிங் செய்யுங்கள்',
    remove: 'நீக்கு',
    checkout: 'வாங்குதல்',
    shippingInfo: 'கப்பல் தகவல்',
    firstName: 'முதல் பெயர்',
    lastName: 'கடைசி பெயர்',
    email: 'மின்னஞ்சல் முகவரி',
    phone: 'தொலைபேசி எண்',
    address: 'முகவரி',
    city: 'நகரம்',
    state: 'மாநிலம்',
    pincode: 'அஞ்சல் குறியீடு',
    orderSummary: 'ஆர்டர் சுருக்கம்',
    placeOrder: 'ஆர்டர் வைக்கவும்',
    payment: 'கட்டணம்',
    selectPayment: 'கட்டண முறையை தேர்ந்தெடுக்கவும்',
    upi: 'யூபிஐ',
    card: 'கிரெடிட் / டெபிட் கார்டு',
    cod: 'பணச் செலுத்தல் (COD)',
    payNow: 'இப்போது செலு',
    orderSuccess: 'கட்டணம் வெற்றிகரமாக செலுத்தப்பட்டது!',
    orderSuccessMsg: 'உங்கள் ஆர்டர் வைக்கப்பட்டது. நன்றி!',
    backHome: 'முகப்புக்கு திரும்பு',
    yourWishlist: 'உங்கள் விருப்பப் பட்டியல்',
    emptyWishlist: 'உங்கள் விருப்பப் பட்டியல் காலியாக உள்ளது.',
    addToCart: 'வண்டியில் சேர்க்கவும்',
    addedToCart: 'வண்டியில் சேர்க்கப்பட்டது!',
    addedToWishlist: 'விருப்பப் பட்டியலில் சேர்க்கப்பட்டது!',
    removeWishlist: 'நீக்கு',
    reviews: 'விமர்சனங்கள்',
    availability: 'கிடைக்கும் தன்மை',
    available: 'கிடைக்கிறது',
    profile: 'சுயவிவரம்',
    freeShipping: 'இலவச கப்பல்',
    onOrderAbove: '₹900-க்கு மேல் ஆர்டரில்',
    searchPlaceholder: 'தேடு',
    shipping: 'கப்பல் கட்டணம்',
    free: 'இலவசம்',
    grandTotal: 'மொத்த தொகை',
    upiId: 'UPI ID உள்ளிடவும் (எ.கா. name@upi)',
    cardNumber: 'கார்டு எண்',
    expiry: 'காலாவதி (MM/YY)',
    cvv: 'CVV',
    upiVerify: 'சரிபார்த்து செலுத்துக',
    orderPlaced: 'ஆர்டர் வெற்றிகரமாக வைக்கப்பட்டது!',
    thankYou: 'எங்களிடம் கொள்முதல் செய்ததற்கு நன்றி.',
    orderId: 'ஆர்டர் ஐடி',
    topSelling: 'சிறந்த விற்பனை ஆயுர்வேத மருந்துகள்',
    exploreMore: 'சிறந்த மதிப்பீட்டு ஆயுர்வேத மருந்துகளை ஆராயுங்கள்',
    naturalHealthcare: 'ஆயுர்வேதத்துடன் இயற்கை சுகாதாரம்',
    bundle: 'தொகுப்பு',
  },
};

const LangContext = createContext();

export const LangProvider = ({ children }) => {
  const [lang, setLang] = useState('en');
  const t = (key) => translations[lang][key] || key;
  const toggleLang = () => setLang(prev => prev === 'en' ? 'ta' : 'en');
  return (
    <LangContext.Provider value={{ lang, t, toggleLang }}>
      {children}
    </LangContext.Provider>
  );
};

export const useLang = () => useContext(LangContext);
