import React, { createContext, useContext, useState } from 'react';

const translations = {
  en: {
    // ── Nav / Global ──────────────────────────────────────────────────────────
    home: 'HOME',
    aboutUs: 'ABOUT US',
    siddhar: 'SIDDHAR',
    collections: 'COLLECTIONS',
    wishlist: 'WISHLIST',
    login: 'LOGIN',
    createAccount: 'CREATE AN ACCOUNT',
    cart: 'CART',
    switchLang: 'தமிழ்',
    orderOnline: 'Order Online or Call Us',
    freeShipping: 'FREE Shipping',
    onOrderAbove: 'ON ORDER ABOVE ₹900',
    onlySelected: '(Only On Selected Items)',
    searchPlaceholder: 'Search',
    signIn: 'Sign In',
    myAccount: 'My Account',
    // ── Footer ────────────────────────────────────────────────────────────────
    footerTagline: 'Authentic Ayurvedic & Siddha medicines delivered to your door.',
    informations: 'Informations',
    whatIsSiddhar: 'What Is Siddhar?',
    siddharWellness: 'Siddhar Wellness',
    search: 'Search',
    privacyPolicy: 'Privacy Policy',
    termsConditions: 'Terms & Conditions',
    sitemap: 'Sitemap',
    customerServices: 'Customer Services',
    contactUs: 'Contact Us',
    internationalShipping: 'International Shipping',
    returnsRefunds: 'Returns & Refunds',
    shippingDelivery: 'Shipping & Delivery',
    quickShop: 'Quick Shop',
    createAnAccount: 'Create an Account',
    stayConnected: 'Stay Connected',
    allRightsReserved: 'All Rights Reserved.',
    termsOfService: 'Terms of Service',
    refundPolicy: 'Refund Policy',
    // ── Home ──────────────────────────────────────────────────────────────────
    shopNow: 'Shop Now',
    bookConsultation: 'Book Consultation',
    buyAyurvedic: "Buy Ayurvedic Medicine Online from India's Largest Siddha Shopping Store",
    buyAyurvedicSub: 'Vel Siddhar Arakkattalai sells all kinds of Ayurvedic & Siddha medicines from top brands like Kottakkal Arya Vaidya Sala, Vaidyaratnam, AVP, Kerala Ayurveda, Himalaya, Dabur & more.',
    exploreAllProducts: 'Explore All Products',
    hundredNaturalFeat: '100% Natural',
    hundredNaturalDesc: 'All products are pure, natural, and free from harmful chemicals.',
    fastDelivery: 'Fast Delivery',
    fastDeliveryDesc: 'Free shipping on orders above ₹900. Quick and safe packaging.',
    trustedQuality: 'Trusted Quality',
    trustedQualityDesc: 'Sourced from certified Ayurvedic manufacturers across India.',
    certifiedProducts: 'Certified Products',
    certifiedProductsDesc: 'All medicines are GMP certified and clinically validated.',
    topSelling: 'Top Selling Ayurvedic Medicines',
    exploreMore: 'Explore our best-rated Ayurvedic & Siddha products',
    addToCartBtn: 'Add to Cart',
    shopByCategory: 'Shop by Category',
    shopByCategorySub: 'Find the perfect Ayurvedic solution for your needs',
    naturalHealthcare: 'Natural Healthcare with Ayurveda & Siddha',
    naturalHealthcareSub: 'Ayurveda, an ancient tradition of medicine in India, is focused on the idea that \'Prevention is better than cure.\' Siddha medicine, derived from Tamil tradition, complements Ayurveda with time-tested formulations for holistic wellness.',
    naturalHealthcareSub2: 'At Vel Siddhar Arakkattalai, we bring you the finest authentic products from India\'s most trusted Ayurvedic and Siddha medicine brands — all at your fingertips with fast, secure delivery.',
    learnAboutSiddhar: 'Learn About Siddhar',
    browseProducts: 'Browse Products',
    // ── Collections / Product ─────────────────────────────────────────────────
    allCollections: 'All Collections',
    discoverRange: 'Discover our authentic range of natural remedies and personal care products.',
    filterByCategory: 'Filter by Category',
    priceRange: 'Price Range',
    allPrices: 'All Prices',
    under100: 'Under ₹100',
    between100and500: '₹100 - ₹500',
    between500and1000: '₹500 - ₹1000',
    over1000: 'Over ₹1000',
    sortBy: 'Sort by',
    defaultSort: 'Default',
    priceLowHigh: 'Price: Low to High',
    priceHighLow: 'Price: High to Low',
    filters: 'Filters',
    results: 'results',
    noProducts: 'No products found matching your criteria.',
    clearFilters: 'Clear Filters',
    // ── Product Detail ────────────────────────────────────────────────────────
    back: 'Back',
    inclusiveTaxes: '(Inclusive of taxes)',
    inStock: 'Availability: In Stock',
    gmpCertified: 'GMP Certified',
    freeShippingAbove: 'Free shipping above ₹900',
    addedToCart: 'Added to Cart!',
    addedToWishlist: 'Added to Wishlist!',
    addToWishlist: 'Add to Wishlist',
    inWishlist: 'In Wishlist',
    addToCart: 'ADD TO CART',
    productDetails: 'Product Details',
    keyBenefits: 'Key Benefits',
    policies: 'Policies',
    disclaimer: 'Disclaimer',
    relatedProducts: 'Related Products',
    reviews: 'reviews',
    exchangeReturn: 'Exchange or Return within 7 days of delivery.',
    freeShippingPolicy: 'Free shipping on orders above ₹900.',
    internationalCall: 'For international shipping, call: +91 96292 97111.',
    disclaimerText: 'Results may vary from person to person. This product is not intended to diagnose, treat, cure or prevent any disease. Consult an Ayurvedic practitioner before use if you have any medical conditions or are pregnant/nursing.',
    benefitNatural: '100% natural ingredients — free from artificial additives',
    benefitClassical: 'Prepared using classical Ayurvedic methods',
    benefitGMP: 'GMP certified manufacturing facility',
    benefitSafe: 'Safe for regular use under guidance',
    benefitHolistic: 'Supports holistic health and wellness',
    // ── Cart ─────────────────────────────────────────────────────────────────
    yourCart: 'Your Cart',
    cartEmpty: 'Your Cart is Empty',
    cartEmptySub: 'Looks like you haven\'t added anything to your cart yet.',
    continueShopping: 'Continue Shopping',
    product: 'PRODUCT',
    price: 'PRICE',
    quantity: 'QUANTITY',
    total: 'TOTAL',
    action: 'ACTION',
    subtotal: 'Subtotal',
    shipping: 'Shipping',
    free: 'FREE',
    grandTotal: 'Grand Total',
    proceedCheckout: 'Proceed to Checkout',
    remove: 'Remove',
    // ── Checkout ──────────────────────────────────────────────────────────────
    checkout: 'Checkout',
    shippingInfo: 'Shipping Information',
    firstName: 'First Name',
    lastName: 'Last Name',
    email: 'Email Address',
    phone: 'Phone Number',
    address: 'Address',
    city: 'City',
    state: 'State',
    pincode: 'Pincode',
    orderSummary: 'Order Summary',
    placeOrder: 'Place Order',
    // ── Payment ───────────────────────────────────────────────────────────────
    payment: 'Payment',
    selectPayment: 'Select Payment Method',
    upi: 'UPI',
    card: 'Credit / Debit Card',
    cod: 'Cash on Delivery',
    payNow: 'Pay Now',
    orderSuccess: 'Payment Successful!',
    orderSuccessMsg: 'Your order has been placed. Thank you!',
    backHome: 'Back to Home',
    orderPlaced: 'Order Placed Successfully!',
    thankYou: 'Thank you for shopping with us.',
    orderId: 'Order ID',
    upiId: 'Enter UPI ID (e.g. name@upi)',
    cardNumber: 'Card Number',
    expiry: 'Expiry (MM/YY)',
    cvv: 'CVV',
    upiVerify: 'Verify & Pay',
    // ── Wishlist ──────────────────────────────────────────────────────────────
    yourWishlist: 'Your Wishlist',
    emptyWishlist: 'Your wishlist is empty.',
    emptyWishlistSub: 'Save products you love and come back to them anytime.',
    removeWishlist: 'Remove',
    moveToCart: 'Move to Cart',
    // ── Login ─────────────────────────────────────────────────────────────────
    welcomeBack: 'Welcome Back',
    loginSubtitle: 'Please enter your details to access your account.',
    username: 'Username',
    password: 'Password',
    enterUsername: 'Enter your Email',
    enterPassword: 'Enter your password',
    rememberMe: 'Remember for 30 days',
    forgotPassword: 'Forgot password?',
    signingIn: 'Authenticating...',
    signInBtn: 'Sign In',
    noAccount: "Don't have an account?",
    signUpToday: 'Sign up today',
    // ── Signup ────────────────────────────────────────────────────────────────
    createYourAccount: 'Create Your Account',
    signupSubtitle: 'Join us and discover authentic Ayurvedic wellness.',
    fullName: 'Full Name',
    enterFullName: 'Enter your full name',
    confirmPassword: 'Confirm Password',
    confirmPasswordPlaceholder: 'Re-enter your password',
    createAccountBtn: 'Create Account',
    alreadyHaveAccount: 'Already have an account?',
    signInLink: 'Sign in here',
    // ── Profile ───────────────────────────────────────────────────────────────
    myProfile: 'My Profile',
    accountInfo: 'Account Information',
    orderHistory: 'Order History',
    noOrders: 'No orders placed yet.',
    logout: 'Logout',
    // ── About Us ──────────────────────────────────────────────────────────────
    ourHeritage: 'Our Heritage',
    heritageText: 'We bring to you the traditional wisdom of Ayurveda combined with modern science. Our mission is to provide 100% natural, safe, and effective Ayurvedic medicines and personal care products. For over three decades, we have been a trusted name in healthcare, focusing on holistic healing and well-being.',
    qualityFirst: 'Quality First',
    qualityText: 'Every product in our store is carefully curated. We partner with top Ayurvedic brands like Kottakkal Arya Vaidya Sala and others to ensure authenticity. From farm to shelf, we ensure strict hygiene and quality protocols.',
    expertDoctors: 'Expert Ayurvedic Doctors',
    expertDoctorsSub: 'Consult with our specialists for a healthier life.',
    // ── E-Consultation ────────────────────────────────────────────────────────
    eConsultTitle: 'E-Consultation (Book Now)',
    eConsultSub: 'Get personalized health advice from expert Ayurvedic physicians entirely online.',
    bookingConfirmed: 'Booking Confirmed!',
    bookingConfirmedMsg: 'We have sent the consultation link to your email. Our doctor will be with you shortly.',
    bookAppointment: 'Book an Appointment',
    fillDetails: 'Fill out details below',
    fullNameLabel: 'Full Name',
    phoneLabel: 'Phone Number',
    preferredDate: 'Preferred Date',
    preferredTime: 'Preferred Time',
    selectSlot: 'Select a slot',
    morning: 'Morning (10 AM - 12 PM)',
    afternoon: 'Afternoon (2 PM - 5 PM)',
    evening: 'Evening (6 PM - 8 PM)',
    healthIssue: 'Describe Your Health Issue',
    healthIssuePlaceholder: 'e.g. Seeking consultation for joint pain and fatigue...',
    confirmBooking: 'Confirm Booking',
    // ── Personal Care ─────────────────────────────────────────────────────────
    personalCare: 'Personal Care',
    theSiddhaWay: 'The Siddha Way',
    naturalAndAuthentic: 'Natural & Authentic',
    shopPersonalCare: 'Shop Personal Care',
    freeSkinConsultation: 'Free Skin Consultation',
    browseByCategory: 'Browse by Category',
    findPerfectCare: 'Find the perfect care for every part of you',
    ourProducts: 'Our Products',
    authenticProducts: 'Authentic Siddha personal care, naturally crafted',
    searchProducts: 'Search products...',
    viewAllPersonalCare: 'View All Personal Care Products',
    whyChoosePersonalCare: 'Why Choose Our Personal Care?',
    siddhaAdvantage: 'The Siddha advantage for your everyday care routine',
    wellnessTips: 'Siddha Wellness Tips',
    ancientRoutines: 'Ancient routines for modern glowing skin & healthy hair',
    customersSay: 'What Our Customers Say',
    realResults: 'Real results from real people with our natural products',
    naturalJourney: 'Start Your Natural Skincare Journey Today',
    notSureConsult: 'Not sure what\'s right for your skin or hair? Book a free online consultation with our Siddha experts.',
    bookFreeConsultation: 'Book Free Consultation',
    faceCareCat: 'Face Care',
    hairCareCat: 'Hair Care',
    bodyCareCat: 'Body Care',
    herbalOilsCat: 'Herbal Oils',
    faceCareDesc: 'Cleansers, face packs, serums & moisturisers',
    hairCareDesc: 'Oils, shampoos, conditioners & hair masks',
    bodyCareDesc: 'Scrubs, lotions, bath oils & soaps',
    herbalOilsDesc: 'Medicated oils for skin, scalp & massage',
    fivePlusProd: '50+ Personal Care Products',
    hundredNatural: '100% Natural Ingredients',
    happyCustomers: '2500+ Happy Customers',
    yearsHeritage: '30+ Years of Heritage',
    allPersonalCare: 'All Personal Care',
    aboutSection: 'About',
    ayurvedicTips: 'Ayurvedic Tips',
    recommendedProducts: 'Recommended Products',
    notSureWhatsRight: "Not sure what's right for you?",
    getFreeConsultation: 'Get a free personalised consultation from our Siddha experts.',
    noProductsYet: 'No products available yet. Check back soon!',
    browseAllCollections: 'Browse All Collections',
    group1: 'Ayurvedic Medicine For',
    group2: 'Ayurvedic Products For',
    group3: 'Digestive & Metabolic Care',
    // ── 404 ──────────────────────────────────────────────────────────────────
    pageNotFound: 'Page Not Found',
    pageNotFoundSub: 'The page you are looking for doesn\'t exist or has been moved.',
    goHome: 'Go to Homepage',
    // ── Navbar & Footer & Profile Extra ───────────────────────────────────────
    brandVelSiddhar: 'Vel Siddhar',
    brandArakkattalai: 'Arakkattalai',
    address: 'Address',
    emailId: 'velsiddhararakkattalai@gmail.com',
    phoneNum: '+91 94871 87384',
    admin: 'ADMIN',
    myOrders: 'My Orders',
    healthNutrition: 'Health & Nutrition',
    companyProfileTitle: 'Company Profile',
    ourFounder: 'Our Founder',
    coughAndCold: 'Cough and Cold',
    fever: 'Fever',
    migraine: 'Migraine',
    sinus: 'Sinus',
    bodyCare: 'Body Care',
    faceCare: 'Face Care',
    ayurvedicHairOil: 'Ayurvedic Hair Oil',
    skinBeautyCare: 'Skin & Beauty Care',
    constipation: 'Constipation',
    diabetesControl: 'Diabetes / Sugar Control',
    digestion: 'Digestion',
    gastroHealth: 'Gastro Health & Acidity',
    obesity: 'Obesity',
    pilesHemorrhoid: 'Piles & Hemorrhoid',
    cpHeading: 'Vel Siddhar Vaithiyasala — Company Profile',
    cpSubheading: 'Seven Generations of Siddha Wisdom, One Mission of Healing',
    cpP1: 'Vel Siddhar Vaithiyasala is a traditional Siddha herbal clinic rooted in an unbroken lineage of healing knowledge passed down through seven generations. What began as a calling to serve the ailing with nature\'s own remedies has grown into a trusted name for authentic Siddha treatment in the region.',
    cpP2: 'Siddha medicine is one of the world\'s oldest medical systems, originating in Tamil Nadu and refined by the great Siddhar saints. Unlike modern medicine that often addresses symptoms alone, Siddha healing seeks to identify and eliminate the root cause of disease — restoring balance between body, mind, and spirit through natural herbs, minerals, and time-proven therapies.',
    cpP3: 'At our clinic, we offer effective Siddha treatment for joint pain, nerve-related disorders, skin diseases, piles, and a wide range of chronic conditions. Our traditional herbal formulations are prepared with care, following age-old methods handed down through our family lineage — ensuring purity, potency, and safety in every remedy.',
    cpP4: 'Our approach is patient-first. We believe that true healing takes patience and precision. That is why we take time to understand each patient\'s unique constitution and Medical history before recommending a treatment. Many patients have experienced significant relief within just 7 days of beginning our Siddha course.',
    cpP5: 'We remain committed to preserving and sharing this ancient science with the modern world. Whether you are seeking relief from a long-standing condition or simply wish to maintain Your health naturally, Vel Siddhar Vaithiyasala welcomes you with warmth, honesty, and generations of healing knowledge.',
    exploreCollections: 'Explore Our Collections',
    // ── Product Filters ───────────────────────────────────────────────────────
    'BROWSE CATEGORIES': 'BROWSE CATEGORIES',
    'FILTER BY TYPE': 'FILTER BY TYPE',
    'FILTER BY BRANDS': 'FILTER BY BRANDS',
    'FILTER BY AILMENTS': 'FILTER BY AILMENTS',
    'POPULAR PRODUCTS': 'POPULAR PRODUCTS',
    'Capsules': 'Capsules',
    'Churnam': 'Churnam',
    'Leham': 'Leham',
    'Tailam': 'Tailam',
    'General': 'General',
    'Kottakkal': 'Kottakkal',
    'AVP Ayurveda': 'AVP Ayurveda',
    'Kerala Ayurveda': 'Kerala Ayurveda',
    'AVN': 'AVN',
    'Vaidyaratnam': 'Vaidyaratnam',
    'Classical Medicines': 'Classical Medicines',
    'Cold': 'Cold',
    'Diabetes': 'Diabetes',
    'Sinusitis': 'Sinusitis',
    'Digestion': 'Digestion',
    'Immunity': 'Immunity',
    'Hair': 'Hair',
    'Skin': 'Skin',
    'Stress': 'Stress',
    'Featured': 'Featured',
    'Price: Low to High': 'Price: Low to High',
    'Price: High to Low': 'Price: High to Low',
    'Top Rated': 'Top Rated',
    'Newest': 'Newest',
    'ALL AYURVEDIC PRODUCTS': 'ALL AYURVEDIC PRODUCTS',
    'PRODUCTS': 'PRODUCTS',
    'Showing:': 'Showing:',
    'of': 'of',
    'Clear filters': 'Clear filters',
    'Clear All Filters': 'Clear All Filters',
    'No products found': 'No products found',
    'Try adjusting your filters or browse all collections.': 'Try adjusting your filters or browse all collections.',
    'Clear': 'Clear',
    'Sort': 'Sort',
    // ── Clinic Details ────────────────────────────────────────────────────────
    clinicTitle: 'Vel Siddhar Vaithiyasala',
    clinicSubTitle: '(Herbal Clinic)',
    treatmentTimeframe: 'In Siddha medicine, within 7 days:',
    treatmentList1: 'Treatment is provided for joint pain',
    treatmentList2: 'Nerve-related problems',
    treatmentList3: 'Skin diseases',
    treatmentList4: 'Piles',
    treatmentList5: 'And various other chronic illnesses',
    aboutUsClinic: 'About Us',
    clinicDesc1: 'At Vel Siddhar Vaithiyasala, we practice Siddha medicine rooted in knowledge passed down through seven generations. Our clinic is dedicated to providing traditional and natural healing for a wide range of health conditions.',
    clinicDesc2: 'We offer treatment for joint pain, nerve-related disorders, skin diseases, piles, and various chronic illnesses. Our approach focuses on effective, time-tested Siddha methods that aim to treat the root cause and promote overall well-being.',
    treatmentDesc: 'Complete cure is offered through traditional Siddha methods.',
    doctorName: 'Dr. S. Kuresan',
    doctorQual: 'M.A., S.M.P., S.M.T.P., Doc. Alt. M.',
    doctorRole: 'Siddha Physician & Traditional Healer',
    contactLabel: 'Contact',
    contactNumber: '9487187384',
    addressLabel: 'Address',
    addressLine1: 'Near U.G.P. Complex,',
    addressLine2: 'Annan Bus Stand,',
    addressLine3: 'Nagercoil',
    // ── About Us Extra ───────────────────────────────────────────────────────
    siddhaClinic: 'Siddha Herbal Clinic',
    clinicSlogan: 'Seven generations of Siddha healing wisdom — rooted in tradition, backed by nature, dedicated to your complete wellness.',
    callNow: 'Call Now',
    whatsapp: 'WhatsApp',
    verifiedSpecialist: 'Verified Specialist',
    ratingValue: '5.0 Rating',
    genOfSiddhar: 'Generations of Siddha',
    patientsTreated: '12K+ Patients Treated',
    reliefGuaranteed: '7 Days Relief',
    herbalFormulas: '200+ Herbal Formulas',
    aboutTheClinic: 'About The Clinic',
    healingAncient: 'Healing Through Ancient Siddha Wisdom',
    rootCause: 'Root Cause Treatment',
    noSideEffects: 'No Side Effects',
    traditionalHerbs: 'Traditional Herbs',
    certifiedPhysician: 'Certified Physician',
    clinicTimings: 'Clinic Timings',
    monSat: 'Mon – Sat',
    sun: 'Sunday',
    closed: 'Closed',
    emergency: 'Emergency',
    whatsapp247: 'WhatsApp 24/7',
    conditionsWeTreat: 'Conditions We Treat',
    conditionsSub: 'Effective Siddha treatments for a wide range of chronic and acute health conditions.',
    jointPainTitle: 'Joint Pain Treatment',
    jointPainDesc: 'Effective Siddha therapy for arthritis, knee pain, and musculoskeletal disorders.',
    nerveDisTitle: 'Nerve Disorders',
    nerveDisDesc: 'Traditional remedies for nerve-related conditions, paralysis and neurological issues.',
    skinDisTitle: 'Skin Diseases',
    skinDisDesc: 'Herbal formulations for psoriasis, eczema, fungal infections and chronic skin conditions.',
    pilesTitle: 'Piles Treatment',
    pilesDesc: 'Safe and proven Siddha medicine for hemorrhoid relief without surgery.',
    chronicTitle: 'Chronic Illnesses',
    chronicDesc: 'Holistic care for diabetes, hypertension, and other long-standing health conditions.',
    herbalFormTitle: 'Herbal Formulations',
    herbalFormDesc: 'Authentic Siddha medicines prepared using traditional 7-generation family recipes.',
    whyChooseClinic: 'Why Choose Our Clinic?',
    safeNatural: 'Safe & Natural',
    safeNaturalDesc: '100% herbal medicines with no harmful side effects',
    sevenGens: '7 Generations',
    sevenGensDesc: 'Traditional knowledge passed through seven generations',
    rootCure: 'Root Cure',
    rootCureDesc: 'We treat the root cause, not just the symptoms',
    expertDoc: 'Expert Doctor',
    expertDocDesc: 'Qualified Siddha physician with decades of experience',
    reachUs: 'Reach Us',
    contactInfo: 'Contact Information',
    tapToCall: 'Tap to Call',
    email: 'Email',
    sendEmail: 'Send Email',
    getDirections: 'Get Directions',
    findUsMap: 'Find Us On Map',
    ourLoc: 'Our Location',
    clinicAddr: 'Clinic Address',
    startHealing: 'Start Your Healing Journey Today',
    healingExp: 'Experience the power of traditional Siddha medicine. Our doctor is available Mon–Sat, 9 AM – 7 PM. Book a consultation in person or via WhatsApp.',
    chatOnWhatsapp: 'Chat on WhatsApp',
    bookEConsult: 'Book E-Consultation',
    // ── Shipping & Delivery Extra ─────────────────────────────────────────────
    shippingHeroTag: 'Fast, safe, and reliable delivery of Ayurvedic & Siddha medicines across India and worldwide.',
    sameDayDispatch: 'Same Day Dispatch',
    ordersBefore2PM: 'Orders before 2 PM',
    liveTracking: 'Live Tracking',
    viaSMSWhatsapp: 'Via SMS & WhatsApp',
    safePackaging: 'Safe Packaging',
    tamperProofEco: 'Tamper-proof & eco-friendly',
    howOrderTravels: 'How Your Order Travels',
    orderJourneySub: 'From our warehouse to your doorstep — every step tracked.',
    orderPlacedStep: 'Order Placed',
    orderPlacedDesc: 'Your order is confirmed and payment received.',
    qualityCheckStep: 'Quality Check',
    qualityCheckDesc: 'Products are verified and carefully packed.',
    dispatchedStep: 'Dispatched',
    dispatchedDesc: 'Handed over to our logistics partner.',
    inTransitStep: 'In Transit',
    inTransitDesc: 'Tracking updates sent to your email/WhatsApp.',
    deliveredStep: 'Delivered',
    deliveredDesc: 'Package delivered to your doorstep.',
    ourShippingPolicies: 'Our Shipping Policies',
    shippingPoliciesSub: 'Everything you need to know before you order.',
    domesticShippingTitle: 'Domestic Shipping (India)',
    standardDelivery: 'Standard delivery: 5–7 business days across India',
    expressDelivery: 'Express delivery: 2–3 business days (metro cities)',
    freeShippingAbove900: 'Free shipping on orders above ₹900 (selected items)',
    dispatchSameDay: 'Orders placed before 2 PM are dispatched the same day',
    shipAllStates: 'We ship to all 28 states and 8 Union Territories',
    intlShippingTitle: 'International Shipping',
    shipGlobal: 'We ship to 50+ countries worldwide',
    intlDeliveryTime: 'Delivery takes 10–15 business days after dispatch',
    dutyResponsibility: 'Customs duties and taxes are the buyer\'s responsibility',
    herbalRestricted: 'Some herbal liquids may be restricted by customs regulations',
    intlQueries: 'For international queries, call: +91 96292 97111',
    pkgStandardsTitle: 'Packaging Standards',
    ecoTamperPkg: 'All items packed in eco-friendly, tamper-proof packaging',
    bubbleWrapPkg: 'Liquid & glass items are individually bubble-wrapped',
    invoiceIncluded: 'Invoice included inside every package',
    plainBoxPkg: 'Outer box is plain — no product branding for privacy',
    coldChainPkg: 'Cold-chain packaging available for sensitive formulations',
    cancelAddressTitle: 'Cancellations & Address Changes',
    cancelWithin2h: 'Orders can be cancelled within 2 hours of placing',
    addrWithin2h: 'Address changes must be requested within 2 hours',
    prepaidRefund: 'Prepaid orders: refund within 5–7 business days',
    dispatchedNoCancel: 'Once dispatched, cancellations are not possible',
    whatsappUrgent: 'Contact us immediately via WhatsApp for urgent changes',
    faqTitle: 'Frequently Asked Questions',
    faqSub: 'Common shipping questions answered for you.',
    faqQ1: 'How long does delivery take within India?',
    faqA1: 'Standard delivery takes 5–7 business days. Express delivery takes 2–3 business days. Remote/hilly areas may take 1–2 extra days. Orders placed before 2 PM are dispatched the same day (Mon–Sat).',
    faqQ2: 'Is there free shipping?',
    faqA2: 'Yes! We offer FREE standard shipping on all orders above ₹900. This applies to selected items and is valid for delivery within India only.',
    faqQ3: 'Do you ship internationally?',
    faqA3: 'Yes, we ship to most countries worldwide. International shipping charges are calculated at checkout based on destination country and package weight. Estimated delivery is 10–15 business days after dispatch.',
    faqQ4: 'How do I track my order?',
    faqA4: "Once your order is dispatched, you will receive a tracking number via SMS/WhatsApp and email. You can track your package on the carrier's website or by contacting us directly.",
    faqQ5: 'What happens if my package is damaged or lost?',
    faqA5: 'If your order arrives damaged or is lost in transit, please contact us within 48 hours of the expected delivery date. We will either reship the product or issue a full refund after investigation.',
    faqQ6: 'Can I change my delivery address after placing the order?',
    faqA6: 'Address changes can only be made within 2 hours of placing the order, before it is dispatched. Please contact us immediately via phone or WhatsApp to request a change.',
    faqQ7: 'Are there any items that cannot be shipped?',
    faqA7: 'Some liquid herbal preparations may be restricted by certain couriers or international customs regulations. If any item in your order cannot be shipped to your location, we will notify you and offer a full refund.',
    faqQ8: 'How are products packed?',
    faqA8: 'All products are packed in tamper-proof, eco-friendly packaging to ensure they arrive in perfect condition. Fragile items like glass bottles are individually bubble-wrapped.',
    stillHaveQuestions: 'Still have questions?',
    supportTeamHours: 'Our team is available Monday to Saturday, 10 AM – 7 PM IST. Reach us via phone, email, or WhatsApp for instant support.',
    // ── Admin & Extra ────────────────────────────────────────────────────────
    adminDashboard: 'Admin Dashboard',
    addNewProduct: 'Add New Product',
    inventoryMgmt: 'Inventory Management',
    productNameLab: 'Product Name',
    productDescLab: 'Product Description',
    productImgLab: 'Product Image',
    classification: 'Classification',
    categoryLab: 'Category',
    brandLab: 'Brand',
    formTypeLab: 'Form / Type',
    ailmentsLab: 'Ailments / Tags',
    pricing: 'Pricing',
    currentPriceLab: 'Current Price (₹)',
    mrpLab: 'MRP (₹)',
    optional: 'Optional',
    saveProduct: 'Save Product',
    cancel: 'Cancel',
    saving: 'Saving...',
    secureCheckout: 'Secure Checkout • Fast Delivery',
    // ── Home & Categories ───────────────────────────────────────────────────
    heroSlide1Head: 'Ancient Wisdom,\nModern Wellness',
    heroSlide1Sub: 'Authentic Siddha & Ayurvedic medicines delivered to your door',
    heroSlide2Head: 'Pure. Natural.\nAuthentic.',
    heroSlide2Sub: "Shop India's finest Ayurvedic products from trusted brands",
    heroSlide3Head: 'Heal Naturally,\nLive Fully',
    heroSlide3Sub: 'Certified Ayurvedic medicines for every need',
    catSiddhar: 'Siddhar',
    catClassical: 'Classical Medicines',
    catPersonalCare: 'Personal Care',
    catBrands: 'Brands',
    catHealthNutrition: 'Health & Nutrition',
    catGeneral: 'General',
    chatOnWhatsappTitle: 'Chat with us on WhatsApp',
    // ── Personal Care ────────────────────────────────────────────────────────
    pcHeroMain: 'TIMELESS \n SIDDHA BEAUTY',
    pcHeroSub: '"Your body is a temple; treat it with the sacred wisdom of ancient healers."',
    pcBuildRegimen: 'BUILD YOUR REGIMEN',
    pcExploreAll: 'EXPLORE ALL',
    pcPillarsHead: 'THE THREE \n PILLARS OF RADIANCE',
    pcPillarsSub: 'Siddha medicine views personal care as an internal and external harmony of the Three Humors (Mukkutram).',
    pcPithamTitle: 'Pitham',
    pcPithamFocus: 'Brightness & Heat',
    pcPithamDesc: 'Balancing Pitta addresses inflammation, sensitivity, and redness.',
    pcVadhamTitle: 'Vadham',
    pcVadhamFocus: 'Moisture & Flow',
    pcVadhamDesc: 'Vata care prevents dryness, thin hair, and premature aging.',
    pcKabamTitle: 'Kabam',
    pcKabamFocus: 'Firmness & Oil',
    pcKabamDesc: 'Kapha balancing controls excess oil and maintains skin elasticity.',
    pcPersonalizedCare: 'Personalized Care',
    pcCraftRitual: 'CRAFT YOUR RITUAL',
    pcCleanseTitle: 'Cleanse',
    pcCleanseSub: 'Remove Toxins',
    pcCleanseDesc: 'Ancient blends to purify skin without stripping natural oils.',
    pcNourishTitle: 'Nourish',
    pcNourishSub: 'Deep Hydration',
    pcNourishDesc: 'Sacred oils and herb-infused serums for cell-level restoration.',
    pcHealTitle: 'Heal',
    pcHealSub: 'Targeted Care',
    pcHealDesc: 'Specific formulations for acne, pigmentation, and hair health.',
    pcProtectTitle: 'Protect',
    pcProtectSub: 'Daily Shield',
    pcProtectDesc: 'Lightweight barriers that shield from pollution and oxidation.',
    pcOnlyFromEarth: 'ONLY FROM \n THE EARTH',
    pcNeemTurmeric: 'NEEM & TURMERIC',
    pcGoldenHealers: '"The Golden Healers of the East"',
    pcHeritage: 'ESTD.\n1994\nHERITAGE',
    pcSacredSourcing: 'Sacred Sourcing',
    pcSacredSourcingDesc: 'We pick herbs at the peak of their astrological potency, as prescribed in ancient Siddha manuscripts.',
    pcSlowExtraction: 'Slow Extraction',
    pcSlowExtractionDesc: 'No heat. No chemicals. Only the sun and time are used to extract the healing essence of our botanicals.',
    pcPurityCertified: 'Purity Certified',
    pcPurityCertifiedDesc: 'Every batch is tested to be 100% free of parabens, sulphates, and synthetic fragrances.',
    pcBelovedModern: 'BELOVED BY \n THE MODERN USER',
    pcBelovedSub: "Ancient solutions meeting the needs of today's urban lifestyle.",
    pcVoicesWellness: 'VOICES OF WELLNESS',
    pcVoicesSub: 'How Siddha wisdom has transformed the lives of our global community.',
    pcVerifiedPurchase: 'Verified Purchase',
    pcStartJourney: 'START YOUR JOURNEY',
    pcBookFreeConsult: 'BOOK FREE CONSULTATION',
    pcBrowseRituals: 'BROWSE RITUALS',
  },

  ta: {
    // ── Nav / Global ──────────────────────────────────────────────────────────
    home: 'முகப்பு',
    aboutUs: 'எங்களை பற்றி',
    siddhar: 'சித்தர்',
    collections: 'தொகுப்புகள்',
    wishlist: 'விருப்பப் பட்டியல்',
    login: 'உள்நுழைவு',
    createAccount: 'கணக்கு உருவாக்கு',
    cart: 'வண்டி',
    switchLang: 'English',
    orderOnline: 'ஆன்லைனில் ஆர்டர் செய்யுங்கள் அல்லது அழைக்கவும்',
    freeShipping: 'இலவச கப்பல்',
    onOrderAbove: '₹900-க்கு மேல் ஆர்டரில்',
    onlySelected: '(தேர்ந்தெடுக்கப்பட்ட பொருட்களில் மட்டுமே)',
    searchPlaceholder: 'தேடு',
    signIn: 'உள்நுழை',
    myAccount: 'என் கணக்கு',
    // ── Footer ────────────────────────────────────────────────────────────────
    footerTagline: 'நம்பகமான ஆயுர்வேத & சித்த மருந்துகள் உங்கள் வீட்டிற்கு.',
    informations: 'தகவல்கள்',
    whatIsSiddhar: 'சித்தர் என்றால் என்ன?',
    siddharWellness: 'சித்தர் நலவாழ்வு',
    search: 'தேடு',
    privacyPolicy: 'தனியுரிமைக் கொள்கை',
    termsConditions: 'விதிமுறைகள் & நிபந்தனைகள்',
    sitemap: 'தள வரைபடம்',
    customerServices: 'வாடிக்கையாளர் சேவைகள்',
    contactUs: 'தொடர்பு கொள்ளுங்கள்',
    internationalShipping: 'சர்வதேச கப்பல்',
    returnsRefunds: 'திரும்பல் & திரும்பப் பெறுதல்',
    shippingDelivery: 'கப்பல் & டெலிவரி',
    quickShop: 'விரைவு கடை',
    createAnAccount: 'கணக்கு உருவாக்கு',
    stayConnected: 'தொடர்பில் இருங்கள்',
    allRightsReserved: 'அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை.',
    termsOfService: 'சேவை விதிமுறைகள்',
    refundPolicy: 'திரும்பப் பெறும் கொள்கை',
    // ── Home ──────────────────────────────────────────────────────────────────
    shopNow: 'இப்போதே வாங்கவும்',
    bookConsultation: 'ஆலோசனை பதிவு',
    buyAyurvedic: 'இந்தியாவின் மிகப்பெரிய சித்த கடையில் இருந்து ஆன்லைனில் ஆயுர்வேத மருந்துகள் வாங்கவும்',
    buyAyurvedicSub: 'வேல் சித்தர் அரக்கட்டளை கொட்டக்கல் ஆர்யா வைத்ய சாலா, வைத்யரத்னம், AVP, கேரள ஆயுர்வேதம், இமாலயா, டாபர் மற்றும் பலவற்றிலிருந்து அனைத்து வகையான ஆயுர்வேத மற்றும் சித்த மருந்துகளை விற்கிறது.',
    exploreAllProducts: 'அனைத்து பொருட்களையும் ஆராயுங்கள்',
    hundredNaturalFeat: '100% இயற்கை',
    hundredNaturalDesc: 'அனைத்து பொருட்களும் தூய்மையான, இயற்கையான மற்றும் தீங்கான இரசாயனங்கள் இல்லாதவை.',
    fastDelivery: 'விரைவு டெலிவரி',
    fastDeliveryDesc: '₹900-க்கு மேல் ஆர்டரில் இலவச கப்பல். விரைவான மற்றும் பாதுகாப்பான பேக்கேஜிங்.',
    trustedQuality: 'நம்பகமான தரம்',
    trustedQualityDesc: 'இந்தியா முழுவதும் சான்றளிக்கப்பட்ட ஆயுர்வேத உற்பத்தியாளர்களிடமிருந்து பெறப்படுகிறது.',
    certifiedProducts: 'சான்றளிக்கப்பட்ட பொருட்கள்',
    certifiedProductsDesc: 'அனைத்து மருந்துகளும் GMP சான்றளிக்கப்பட்டு மருத்துவ ரீதியாக சரிபார்க்கப்பட்டவை.',
    topSelling: 'சிறந்த விற்பனை ஆயுர்வேத மருந்துகள்',
    exploreMore: 'எங்கள் சிறந்த மதிப்பீட்டு ஆயுர்வேத & சித்த பொருட்களை ஆராயுங்கள்',
    addToCartBtn: 'வண்டியில் சேர்',
    shopByCategory: 'வகையின்படி வாங்கவும்',
    shopByCategorySub: 'உங்கள் தேவைக்கு சரியான ஆயுர்வேத தீர்வை கண்டறியுங்கள்',
    naturalHealthcare: 'ஆயுர்வேதம் & சித்தத்துடன் இயற்கை சுகாதாரம்',
    naturalHealthcareSub: 'இந்தியாவின் ஒரு பழங்கால மருத்துவ மரபான ஆயுர்வேதம் "தடுப்பு குணப்படுத்துவதை விட சிறந்தது" என்ற கருத்தை கையாளுகிறது. தமிழ் மரபிலிருந்து வந்த சித்த மருத்துவம் ஆயுர்வேதத்தை முழுமையான நலனுக்கான கால-சோதிக்கப்பட்ட சூத்திரங்களுடன் நிறைவு செய்கிறது.',
    naturalHealthcareSub2: 'வேல் சித்தர் அரக்கட்டளையில், இந்தியாவின் மிகவும் நம்பகமான ஆயுர்வேத மற்றும் சித்த மருந்து பிராண்டுகளிலிருந்து சிறந்த நம்பகமான பொருட்களை வேகமான, பாதுகாப்பான டெலிவரியுடன் உங்கள் விரல் நுனியில் கொண்டு வருகிறோம்.',
    learnAboutSiddhar: 'சித்தரை பற்றி அறியுங்கள்',
    browseProducts: 'பொருட்களை உலாவுங்கள்',
    // ── Collections / Product ─────────────────────────────────────────────────
    allCollections: 'அனைத்து தொகுப்புகள்',
    discoverRange: 'எங்கள் நம்பகமான இயற்கை மருந்துகள் மற்றும் தனிப்பட்ட பராமரிப்பு பொருட்களை கண்டறியுங்கள்.',
    filterByCategory: 'வகையின்படி வடிகட்டு',
    priceRange: 'விலை வரம்பு',
    allPrices: 'அனைத்து விலைகளும்',
    under100: '₹100-க்கு கீழ்',
    between100and500: '₹100 - ₹500',
    between500and1000: '₹500 - ₹1000',
    over1000: '₹1000-க்கு மேல்',
    sortBy: 'வரிசைப்படுத்து',
    defaultSort: 'இயல்பு',
    priceLowHigh: 'விலை: குறைவிலிருந்து அதிகம்',
    priceHighLow: 'விலை: அதிகத்திலிருந்து குறைவு',
    filters: 'வடிகட்டிகள்',
    results: 'முடிவுகள்',
    noProducts: 'உங்கள் தேர்வுக்கு பொருந்தும் பொருட்கள் எதுவும் இல்லை.',
    clearFilters: 'வடிகட்டிகளை அழி',
    // ── Product Detail ────────────────────────────────────────────────────────
    back: 'பின்செல்',
    inclusiveTaxes: '(வரிகள் உட்பட)',
    inStock: 'கிடைக்கும் தன்மை: கையிருப்பில் உள்ளது',
    gmpCertified: 'GMP சான்றளிக்கப்பட்டது',
    freeShippingAbove: '₹900-க்கு மேல் இலவச கப்பல்',
    addedToCart: 'வண்டியில் சேர்க்கப்பட்டது!',
    addedToWishlist: 'விருப்பப் பட்டியலில் சேர்க்கப்பட்டது!',
    addToWishlist: 'விருப்பப் பட்டியலில் சேர்',
    inWishlist: 'விருப்பப் பட்டியலில் உள்ளது',
    addToCart: 'வண்டியில் சேர்',
    productDetails: 'பொருள் விவரங்கள்',
    keyBenefits: 'முக்கிய நன்மைகள்',
    policies: 'கொள்கைகள்',
    disclaimer: 'மறுப்பு',
    relatedProducts: 'தொடர்பான பொருட்கள்',
    reviews: 'விமர்சனங்கள்',
    exchangeReturn: 'டெலிவரி செய்த 7 நாட்களுக்குள் மாற்று அல்லது திரும்பு.',
    freeShippingPolicy: '₹900-க்கு மேல் ஆர்டரில் இலவச கப்பல்.',
    internationalCall: 'சர்வதேச கப்பலுக்கு அழைக்கவும்: +91 96292 97111.',
    disclaimerText: 'முடிவுகள் நபருக்கு நபர் மாறுபடலாம். இந்த பொருள் எந்த நோயையும் கண்டறிக்கவோ, சிகிச்சை செய்யவோ, குணப்படுத்தவோ அல்லது தடுக்கவோ நோக்கமாகவில்லை.',
    benefitNatural: '100% இயற்கை பொருட்கள் — செயற்கை சேர்க்கைகள் இல்லாதவை',
    benefitClassical: 'கிளாசிக்கல் ஆயுர்வேத முறைகளைப் பயன்படுத்தி தயாரிக்கப்பட்டது',
    benefitGMP: 'GMP சான்றளிக்கப்பட்ட உற்பத்தி வசதி',
    benefitSafe: 'வழிகாட்டுதலின் கீழ் வழக்கமான பயன்பாட்டிற்கு பாதுகாப்பானது',
    benefitHolistic: 'முழுமையான ஆரோக்கியம் மற்றும் நலனை ஆதரிக்கிறது',
    // ── Cart ─────────────────────────────────────────────────────────────────
    yourCart: 'உங்கள் வண்டி',
    cartEmpty: 'உங்கள் வண்டி காலியாக உள்ளது',
    cartEmptySub: 'நீங்கள் இன்னும் வண்டியில் எதுவும் சேர்க்கவில்லை.',
    continueShopping: 'ஷாப்பிங் தொடர்க',
    product: 'பொருள்',
    price: 'விலை',
    quantity: 'அளவு',
    total: 'மொத்தம்',
    action: 'செயல்',
    subtotal: 'இடைத்தொகை',
    shipping: 'கப்பல் கட்டணம்',
    free: 'இலவசம்',
    grandTotal: 'மொத்த தொகை',
    proceedCheckout: 'வாங்குவதற்கு தொடர்க',
    remove: 'நீக்கு',
    // ── Checkout ──────────────────────────────────────────────────────────────
    checkout: 'வாங்குதல்',
    shippingInfo: 'கப்பல் தகவல்',
    firstName: 'முதல் பெயர்',
    lastName: 'கடைசி பெயர்',
    email: 'மின்னஞ்சல் முகவரி',
    phone: 'தொலைபேசி எண்',
    address: 'முகவரி',
    city: 'நகரம்',
    state: 'மாநிலம்',
    pincode: 'அஞ்சல் குறியீடு',
    orderSummary: 'ஆர்டர் சுருக்கம்',
    placeOrder: 'ஆர்டர் வைக்கவும்',
    // ── Payment ───────────────────────────────────────────────────────────────
    payment: 'கட்டணம்',
    selectPayment: 'கட்டண முறையை தேர்ந்தெடுக்கவும்',
    upi: 'யூபிஐ',
    card: 'கிரெடிட் / டெபிட் கார்டு',
    cod: 'பணச் செலுத்தல் (COD)',
    payNow: 'இப்போது செலுத்துக',
    orderSuccess: 'கட்டணம் வெற்றிகரமாக செலுத்தப்பட்டது!',
    orderSuccessMsg: 'உங்கள் ஆர்டர் வைக்கப்பட்டது. நன்றி!',
    backHome: 'முகப்புக்கு திரும்பு',
    orderPlaced: 'ஆர்டர் வெற்றிகரமாக வைக்கப்பட்டது!',
    thankYou: 'எங்களிடம் கொள்முதல் செய்ததற்கு நன்றி.',
    orderId: 'ஆர்டர் ஐடி',
    upiId: 'UPI ID உள்ளிடவும் (எ.கா. name@upi)',
    cardNumber: 'கார்டு எண்',
    expiry: 'காலாவதி (MM/YY)',
    cvv: 'CVV',
    upiVerify: 'சரிபார்த்து செலுத்துக',
    // ── Wishlist ──────────────────────────────────────────────────────────────
    yourWishlist: 'உங்கள் விருப்பப் பட்டியல்',
    emptyWishlist: 'உங்கள் விருப்பப் பட்டியல் காலியாக உள்ளது.',
    emptyWishlistSub: 'நீங்கள் விரும்பும் பொருட்களை சேமித்து எப்போது வேண்டுமானாலும் திரும்பி வாருங்கள்.',
    removeWishlist: 'நீக்கு',
    moveToCart: 'வண்டிக்கு நகர்த்து',
    // ── Login ─────────────────────────────────────────────────────────────────
    welcomeBack: 'மீண்டும் வரவேற்கிறோம்',
    loginSubtitle: 'உங்கள் கணக்கை அணுக விவரங்களை உள்ளிடவும்.',
    username: 'பயனர் பெயர்',
    password: 'கடவுச்சொல்',
    enterUsername: 'உங்கள் மின்னஞ்சலை உள்ளிடவும்',
    enterPassword: 'உங்கள் கடவுச்சொல்லை உள்ளிடவும்',
    rememberMe: '30 நாட்களுக்கு நினைவில் வை',
    forgotPassword: 'கடவுச்சொல் மறந்துவிட்டதா?',
    signingIn: 'உள்நுழைகிறோம்...',
    signInBtn: 'உள்நுழை',
    noAccount: 'கணக்கு இல்லையா?',
    signUpToday: 'இன்றே பதிவு செய்யுங்கள்',
    // ── Signup ────────────────────────────────────────────────────────────────
    createYourAccount: 'உங்கள் கணக்கை உருவாக்குங்கள்',
    signupSubtitle: 'எங்களுடன் இணைந்து நம்பகமான ஆயுர்வேத நலன் கண்டறியுங்கள்.',
    fullName: 'முழு பெயர்',
    enterFullName: 'உங்கள் முழு பெயரை உள்ளிடவும்',
    confirmPassword: 'கடவுச்சொல்லை உறுதிப்படுத்து',
    confirmPasswordPlaceholder: 'கடவுச்சொல்லை மீண்டும் உள்ளிடவும்',
    createAccountBtn: 'கணக்கு உருவாக்கு',
    alreadyHaveAccount: 'ஏற்கனவே கணக்கு உள்ளதா?',
    signInLink: 'இங்கே உள்நுழையுங்கள்',
    // ── Profile ───────────────────────────────────────────────────────────────
    myProfile: 'என் சுயவிவரம்',
    accountInfo: 'கணக்கு தகவல்',
    orderHistory: 'ஆர்டர் வரலாறு',
    noOrders: 'இன்னும் ஆர்டர்கள் எதுவும் இல்லை.',
    logout: 'வெளியேறு',
    // ── About Us ──────────────────────────────────────────────────────────────
    ourHeritage: 'எங்கள் மரபு',
    heritageText: 'நவீன அறிவியலுடன் இணைந்த ஆயுர்வேதத்தின் பாரம்பரிய ஞானத்தை உங்களுக்கு கொண்டு வருகிறோம். 100% இயற்கையான, பாதுகாப்பான மற்றும் பயனுள்ள ஆயுர்வேத மருந்துகளை வழங்குவதே எங்கள் நோக்கம்.',
    qualityFirst: 'தரம் முதலில்',
    qualityText: 'எங்கள் கடையில் உள்ள ஒவ்வொரு பொருளும் கவனமாக தேர்ந்தெடுக்கப்படுகிறது. கொட்டக்கல் ஆர்யா வைத்ய சாலா போன்ற சிறந்த ஆயுர்வேத பிராண்டுகளுடன் பணியாற்றுகிறோம்.',
    expertDoctors: 'நிபுணர் ஆயுர்வேத மருத்துவர்கள்',
    expertDoctorsSub: 'ஆரோக்கியமான வாழ்க்கைக்கு எங்கள் நிபுணர்களிடம் ஆலோசனை பெறுங்கள்.',
    // ── E-Consultation ────────────────────────────────────────────────────────
    eConsultTitle: 'மின் ஆலோசனை (இப்போதே பதிவு செய்யுங்கள்)',
    eConsultSub: 'நிபுணர் ஆயுர்வேத மருத்துவர்களிடமிருந்து ஆன்லைனில் தனிப்பட்ட ஆரோக்கிய ஆலோசனை பெறுங்கள்.',
    bookingConfirmed: 'பதிவு உறுதிப்படுத்தப்பட்டது!',
    bookingConfirmedMsg: 'ஆலோசனை இணைப்பை உங்கள் மின்னஞ்சலுக்கு அனுப்பியுள்ளோம். எங்கள் மருத்துவர் விரைவில் உங்களிடம் வருவார்.',
    bookAppointment: 'சந்திப்பு பதிவு செய்யுங்கள்',
    fillDetails: 'கீழே விவரங்களை பூர்த்தி செய்யுங்கள்',
    fullNameLabel: 'முழு பெயர்',
    phoneLabel: 'தொலைபேசி எண்',
    preferredDate: 'விரும்பிய தேதி',
    preferredTime: 'விரும்பிய நேரம்',
    selectSlot: 'ஒரு நேர இடத்தை தேர்ந்தெடுக்கவும்',
    morning: 'காலை (10 AM - 12 PM)',
    afternoon: 'மதியம் (2 PM - 5 PM)',
    evening: 'மாலை (6 PM - 8 PM)',
    healthIssue: 'உங்கள் உடல்நலப் பிரச்சினையை விளக்குங்கள்',
    healthIssuePlaceholder: 'எ.கா. மூட்டு வலி மற்றும் சோர்வுக்கு ஆலோசனை கோருகிறேன்...',
    confirmBooking: 'பதிவை உறுதிப்படுத்துங்கள்',
    // ── Personal Care ─────────────────────────────────────────────────────────
    personalCare: 'தனிப்பட்ட பராமரிப்பு',
    theSiddhaWay: 'சித்த வழியில்',
    naturalAndAuthentic: 'இயற்கை & நம்பகமான',
    shopPersonalCare: 'தனிப்பட்ட பராமரிப்பு வாங்கவும்',
    freeSkinConsultation: 'இலவச சரும ஆலோசனை',
    browseByCategory: 'வகையின்படி உலாவுங்கள்',
    findPerfectCare: 'உங்களுக்கு சரியான பராமரிப்பை கண்டறியுங்கள்',
    ourProducts: 'எங்கள் பொருட்கள்',
    authenticProducts: 'இயற்கையாக தயாரிக்கப்பட்ட சித்த தனிப்பட்ட பராமரிப்பு',
    searchProducts: 'பொருட்களை தேடுங்கள்...',
    viewAllPersonalCare: 'அனைத்து தனிப்பட்ட பராமரிப்பு பொருட்களையும் காண்க',
    whyChoosePersonalCare: 'ஏன் எங்கள் தனிப்பட்ட பராமரிப்பை தேர்ந்தெடுக்கணும்?',
    siddhaAdvantage: 'உங்கள் தினசரி பராமரிப்புக்கான சித்த சிறப்பு',
    wellnessTips: 'சித்த ஆரோக்கிய குறிப்புகள்',
    ancientRoutines: 'நவீன ஒளிரும் சருமத்திற்கான பழங்கால வழித்தடங்கள்',
    customersSay: 'வாடிக்கையாளர்கள் என்ன சொல்கிறார்கள்',
    realResults: 'இயற்கை பொருட்களால் உண்மையான முடிவுகள்',
    naturalJourney: 'இன்றே உங்கள் இயற்கை சரும பயணத்தை தொடங்குங்கள்',
    notSureConsult: 'உங்கள் சருமம் அல்லது முடிக்கு எது சரியானது என்று தெரியவில்லையா? சித்த நிபுணர்களிடம் இலவச ஆலோசனை பெறுங்கள்.',
    bookFreeConsultation: 'இலவச ஆலோசனை பதிவு செய்யுங்கள்',
    faceCareCat: 'சரும பராமரிப்பு',
    hairCareCat: 'முடி பராமரிப்பு',
    bodyCareCat: 'உடல் பராமரிப்பு',
    herbalOilsCat: 'மூலிகை எண்ணெய்கள்',
    faceCareDesc: 'சுத்தப்படுத்திகள், சரும பேக்குகள், சீரம் & மாய்சர்சர்',
    hairCareDesc: 'எண்ணெய்கள், ஷாம்பு, கண்டிஷனர் & முடி பேக்குகள்',
    bodyCareDesc: 'ஸ்க்ரப்புகள், லோஷன்கள், குளியல் எண்ணெய் & சோப்புகள்',
    herbalOilsDesc: 'சருமம், தலை & மசாஜுக்கான மருந்திட்ட எண்ணெய்கள்',
    fivePlusProd: '50+ தனிப்பட்ட பராமரிப்பு பொருட்கள்',
    hundredNatural: '100% இயற்கை பொருட்கள்',
    happyCustomers: '2500+ மகிழ்ச்சியான வாடிக்கையாளர்கள்',
    yearsHeritage: '30+ ஆண்டுகள் மரபு',
    allPersonalCare: 'அனைத்து தனிப்பட்ட பராமரிப்பு',
    aboutSection: 'பற்றி',
    ayurvedicTips: 'ஆயுர்வேத குறிப்புகள்',
    recommendedProducts: 'பரிந்துரைக்கப்பட்ட பொருட்கள்',
    notSureWhatsRight: 'எது சரியானது என்று தெரியவில்லையா?',
    getFreeConsultation: 'எங்கள் சித்த நிபுணர்களிடம் இலவச ஆலோசனை பெறுங்கள்.',
    noProductsYet: 'பொருட்கள் இன்னும் இல்லை. விரைவில் சரிபாருங்கள்!',
    browseAllCollections: 'அனைத்து தொகுப்புகளையும் உலாவுங்கள்',
    group1: 'ஆயுர்வேத மருத்துவம்',
    group2: 'ஆயுர்வேத பொருட்கள்',
    group3: 'செரிமான & வளர்சிதை மாற்ற பராமரிப்பு',
    // ── 404 ──────────────────────────────────────────────────────────────────
    pageNotFound: 'பக்கம் கண்டுபிடிக்கவில்லை',
    pageNotFoundSub: 'நீங்கள் தேடும் பக்கம் இல்லை அல்லது நகர்த்தப்பட்டுள்ளது.',
    goHome: 'முகப்பு பக்கத்திற்கு செல்லுங்கள்',
    // ── Navbar & Footer & Profile Extra ───────────────────────────────────────
    brandVelSiddhar: 'வேல் சித்தர்',
    brandArakkattalai: 'அறக்கட்டளை',
    address: 'முகவரி',
    emailId: 'velsiddhararakkattalai@gmail.com',
    phoneNum: '+91 94871 87384',
    admin: 'நிர்வாகி (ADMIN)',
    myOrders: 'எனது ஆர்டர்கள்',
    healthNutrition: 'ஆரோக்கியம் மற்றும் ஊட்டச்சத்து',
    companyProfileTitle: 'நிறுவனத்தின் சுயவிவரம்',
    ourFounder: 'எங்கள் நிறுவனர்',
    coughAndCold: 'சளி மற்றும் இருமல்',
    fever: 'காய்ச்சல்',
    migraine: 'ஒற்றைத் தலைவலி',
    sinus: 'சைனஸ்',
    bodyCare: 'உடல் பராமரிப்பு',
    faceCare: 'முகப் பராமரிப்பு',
    ayurvedicHairOil: 'ஆயுர்வேத முடி எண்ணெய்',
    skinBeautyCare: 'சருமம் அழகு பராமரிப்பு',
    constipation: 'மலச்சிக்கல்',
    diabetesControl: 'சர்க்கரை நோய் / நீரிழிவு கட்டுப்பாடு',
    digestion: 'செரிமானம்',
    gastroHealth: 'இரைப்பை மற்றும் நெஞ்செரிச்சல்',
    obesity: 'உடல் பருமன்',
    pilesHemorrhoid: 'மூலம்',
    cpHeading: 'வேல் சித்தர் வைத்தியசாலை — நிறுவனத்தின் சுயவிவரம்',
    cpSubheading: 'ஏழு தலைமுறை சித்த ஞானம், ஒரே குணப்படுத்தும் நோக்கம்',
    cpP1: 'வேல் சித்தர் வைத்தியசாலை என்பது ஏழு தலைமுறைகளாக கடத்தப்பட்ட குணப்படுத்தும் ஞானத்தை அடிப்படையாகக் கொண்ட ஒரு பாரம்பரிய சித்த மூலிகை கிளினிக். இயற்கையின் சொந்த மருந்துகளால் நோயுற்றவர்களுக்கு சேவை செய்யும் ஆர்வத்திலிருந்து தொடங்கியது, இன்று இந்த பிராந்தியத்தில் நம்பகமான சித்த சிகிச்சை நிலையமாக வளர்ந்துள்ளது.',
    cpP2: 'சித்த மருத்துவம் உலகின் மிகப் பழமையான மருத்துவ முறைகளில் ஒன்று, தமிழ்நாட்டில் தோன்றி சித்தர் சாமியார்களால் செம்மைப்படுத்தப்பட்டது. நோயின் அறிகுறிகளை மட்டும் நிவர்த்திக்கும் நவீன மருத்துவத்திலிருந்து வித்தியாசமாக, சித்த குணப்படுத்தல் மூல காரணத்தை கண்டறிந்து நீக்குகிறது — இயற்கை மூலிகைகள், தாதுக்கள் மற்றும் கால-சோதிக்கப்பட்ட சிகிச்சைகள் மூலம் உடல், மனம் மற்றும் ஆன்மாவிற்கு இடையே சமநிலையை மீட்டெடுக்கிறது.',
    cpP3: 'எங்கள் கிளினிக்கில், மூட்டு வலி, நரம்பு சம்பந்தப்பட்ட கோளாறுகள், தோல் நோய்கள், மூலம் மற்றும் பரந்த அளவிலான நாட்பட்ட நிலைகளுக்கு பயனுள்ள சித்த சிகிச்சை வழங்குகிறோம். எங்கள் பாரம்பரிய மூலிகை சூத்திரங்கள் கவனமாக தயாரிக்கப்படுகின்றன, எங்கள் குடும்ப வம்சாவளியில் கடத்தப்பட்ட பழங்கால முறைகளை பின்பற்றி — ஒவ்வொரு மருந்திலும் தூய்மை, வீரியம் மற்றும் பாதுகாப்பை உறுதி செய்கிறோம்.',
    cpP4: 'எங்கள் அணுகுமுறை நோயாளியை முதன்மையாக வைக்கிறது. உண்மையான குணப்படுத்தலுக்கு பொறுமையும் துல்லியமும் தேவை என்று நாங்கள் நம்புகிறோம். அதனால்தான் ஒரு சிகிச்சையை பரிந்துரைக்கும் முன் ஒவ்வொரு நோயாளியின் தனித்துவமான இயல்பு மற்றும் மருத்துவ வரலாற்றை புரிந்துகொள்ள நேரம் எடுக்கிறோம். பல நோயாளிகள் எங்கள் சித்த சிகிச்சையை தொடங்கிய 7 நாட்களுக்குள் குறிப்பிடத்தக்க நிவாரணம் பெற்றுள்ளனர்.',
    cpP5: 'இந்த பண்டைய அறிவியலை நவீன உலகிற்கு பாதுகாத்து பகிர்வதில் நாங்கள் உறுதியாக இருக்கிறோம். நீண்ட காலமாக நீடித்த நிலையிலிருந்து நிவாரணம் தேடுகிறீர்களா அல்லது இயற்கையாக உங்கள் ஆரோக்கியத்தை பராமரிக்க விரும்புகிறீர்களா — வேல் சித்தர் வைத்தியசாலை உங்களை அன்போடு, நேர்மையோடு மற்றும் தலைமுறைகளின் குணப்படுத்தும் ஞானத்துடன் வரவேற்கிறது.',
    exploreCollections: 'எங்கள் தொகுப்புகளை ஆராயுங்கள்',
    // ── Product Filters ───────────────────────────────────────────────────────
    'BROWSE CATEGORIES': 'வகைகளை உலாவு',
    'FILTER BY TYPE': 'வகை மூலம் வடிகட்டு',
    'FILTER BY BRANDS': 'பிராண்ட் மூலம் வடிகட்டு',
    'FILTER BY AILMENTS': 'நோய்கள் மூலம் வடிகட்டு',
    'POPULAR PRODUCTS': 'பிரபலமான பொருட்கள்',
    'Capsules': 'மாத்திரைகள் (Capsules)',
    'Churnam': 'சூரணம் (Churnam)',
    'Leham': 'லேகியம் (Leham)',
    'Tailam': 'தைலம் (Tailam)',
    'General': 'பொது (General)',
    'Kottakkal': 'கொட்டக்கல்',
    'AVP Ayurveda': 'AVP ஆயுர்வேதா',
    'Kerala Ayurveda': 'கேரளா ஆயுர்வேதா',
    'AVN': 'AVN',
    'Vaidyaratnam': 'வைத்யரத்னம்',
    'Classical Medicines': 'பாரம்பரிய மருந்துகள்',
    'Cold': 'சளி',
    'Diabetes': 'நீரிழிவு நோய் (Diabetes)',
    'Sinusitis': 'சைனசிடிஸ் (Sinusitis)',
    'Digestion': 'செரிமானம்',
    'Immunity': 'நோய் எதிர்ப்பு சக்தி',
    'Hair': 'முடி',
    'Skin': 'சருமம்',
    'Stress': 'மன அழுத்தம் (Stress)',
    'Featured': 'சிறப்பு',
    'Price: Low to High': 'விலை: குறைவிலிருந்து அதிகம்',
    'Price: High to Low': 'விலை: அதிகத்திலிருந்து குறைவு',
    'Top Rated': 'சிறந்த மதிப்பீடு',
    'Newest': 'புதியவை',
    'ALL AYURVEDIC PRODUCTS': 'அனைத்து ஆயுர்வேத பொருட்கள்',
    'PRODUCTS': 'பொருட்கள்',
    'Showing:': 'காட்டப்படுவது:',
    'of': 'இல்',
    'Clear filters': 'வடிகட்டிகளை அழி',
    'Clear All Filters': 'அனைத்து வடிகட்டிகளையும் அழி',
    'No products found': 'பொருட்கள் எதுவும் கிடைக்கவில்லை',
    'Try adjusting your filters or browse all collections.': 'உங்கள் வடிகட்டிகளை சரிசெய்ய முயற்சிக்கவும் அல்லது தொகுப்புகளை உலாவவும்.',
    'Clear': 'அழி',
    'Sort': 'வரிசைப்படுத்து',
    // ── Clinic Details ────────────────────────────────────────────────────────
    clinicTitle: 'வேல் சித்தர் வைத்தியசாலை',
    clinicSubTitle: '(மூலிகை கிளினிக்)',
    treatmentTimeframe: 'சித்த மருத்துவத்தில், 7 நாட்களுக்குள்:',
    treatmentList1: 'மூட்டு வலிக்கு சிகிச்சை அளிக்கப்படும்',
    treatmentList2: 'நரம்பு சம்பந்தப்பட்ட பிரச்சனைகள்',
    treatmentList3: 'தோல் வியாதிகள்',
    treatmentList4: 'மூலம்',
    treatmentList5: 'மற்றும் பல்வேறு நாட்பட்ட நோய்கள்',
    aboutUsClinic: 'எங்களை பற்றி',
    clinicDesc1: 'வேல் சித்தர் வைத்தியசாலையில், ஏழு தலைமுறைகளாக கடத்தப்பட்ட அறிவை அடிப்படையாகக் கொண்ட சித்த மருத்துவத்தை நாங்கள் பின்பற்றுகிறோம். பல்வேறு சுகாதார நிலைகளுக்கு பாரம்பரிய மற்றும் இயற்கை குணப்படுத்தும் முறைகளை வழங்குவதில் எங்கள் கிளினிக் அர்ப்பணிக்கப்பட்டுள்ளது.',
    clinicDesc2: 'நாங்கள் மூட்டு வலி, நரம்பு தொடர்பான கோளாறுகள், தோல் நோய்கள், மூலம் மற்றும் பல்வேறு நாட்பட்ட வியாதிகளுக்கு சிகிச்சை அளிக்கிறோம். எங்கள் அணுகுமுறை மூல காரணத்திற்கு சிகிச்சை அளிப்பதை மற்றும் மொத்த நல்வாழ்வை மேம்படுத்துவதை நோக்கமாகக் கொண்ட பயனுள்ள, காலத்தால் சோதிக்கப்பட்ட சித்த முறைகளை மையமாகக் கொண்டுள்ளது.',
    treatmentDesc: 'பழமையான சித்த மருத்துவ முறைகள் மூலம் முழுமையான குணமளிப்பு வழங்கப்படும்.',
    doctorName: 'டாக்டர் எஸ். குரேசன்',
    doctorQual: 'M.A., S.M.P., S.M.T.P., Doc. Alt. M.',
    doctorRole: 'சித்த மருத்துவர் மற்றும் பாரம்பரிய குணப்படுத்துபவர்',
    contactLabel: 'தொடர்புக்கு',
    contactNumber: '9487187384',
    addressLabel: 'முகவரி',
    addressLine1: 'U.G.P. காம்ப்ளக்ஸ் அருகில்,',
    addressLine2: 'அண்ணா பஸ் ஸ்டாண்ட்,',
    addressLine3: 'நாகர்கோவில்',
    // ── About Us Extra ───────────────────────────────────────────────────────
    siddhaClinic: 'சித்த மூலிகை கிளினிக்',
    clinicSlogan: 'ஏழு தலைமுறை சித்த குணப்படுத்தும் ஞானம் — பாரம்பரியத்தில் வேரூன்றி, இயற்கையால் ஆதரிக்கப்பட்டு, உங்கள் முழுமையான ஆரோக்கியத்திற்காக அர்ப்பணிக்கப்பட்டுள்ளது.',
    callNow: 'இப்போதே அழையுங்கள்',
    whatsapp: 'வாட்ஸ்அப்',
    verifiedSpecialist: 'சரிபார்க்கப்பட்ட நிபுணர்',
    ratingValue: '5.0 மதிப்பீடு',
    genOfSiddhar: 'தலைமுறை சித்த மருத்துவம்',
    patientsTreated: '12K+ நோயாளிகள் சிகிச்சை பெற்றுள்ளனர்',
    reliefGuaranteed: '7 நாட்கள் நிவாரணம்',
    herbalFormulas: '200+ மூலிகை சூத்திரங்கள்',
    aboutTheClinic: 'கிளினிக் பற்றி',
    healingAncient: 'பண்டைய சித்த ஞானத்தின் மூலம் குணப்படுத்துதல்',
    rootCause: 'மூல காரண சிகிச்சை',
    noSideEffects: 'பக்க விளைவுகள் இல்லை',
    traditionalHerbs: 'பாரம்பரிய மூலிகைகள்',
    certifiedPhysician: 'சான்றளிக்கப்பட்ட மருத்துவர்',
    clinicTimings: 'கிளினிக் நேரம்',
    monSat: 'திங்கள் – சனி',
    sun: 'ஞாயிறு',
    closed: 'விடுமுறை',
    emergency: 'அவசரம்',
    whatsapp247: 'வாட்ஸ்அப் 24/7',
    conditionsWeTreat: 'நாங்கள் சிகிச்சை அளிக்கும் நோய்கள்',
    conditionsSub: 'பல்வேறு நாட்பட்ட மற்றும் தீவிரமான உடல்நலப் பிரச்சினைகளுக்கு பயனுள்ள சித்த சிகிச்சைகள்.',
    jointPainTitle: 'மூட்டு வலி சிகிச்சை',
    jointPainDesc: 'ஆர்த்ரிடிஸ், முழங்கால் வலி மற்றும் தசைநாண் கோளாறுகளுக்கு பயனுள்ள சித்த சிகிச்சை.',
    nerveDisTitle: 'நரம்பு கோளாறுகள்',
    nerveDisDesc: 'நரம்பு தொடர்பான பிரச்சனைகள், பக்கவாதம் மற்றும் நரம்பியல் பிரச்சினைகளுக்கான பாரம்பரிய மருந்துகள்.',
    skinDisTitle: 'தோல் நோய்கள்',
    skinDisDesc: 'சோரியாசிஸ், எக்ஸிமா, பூஞ்சை தொற்றுகள் மற்றும் நாட்பட்ட தோல் நிலைகளுக்கான மூலிகை மருந்துகள்.',
    pilesTitle: 'மூலம் சிகிச்சை',
    pilesDesc: 'அறுவை சிகிச்சை இல்லாமல் மூலம் நிவாரணத்திற்கு பாதுகாப்பான மற்றும் நிரூபிக்கப்பட்ட சித்த மருந்து.',
    chronicTitle: 'நாட்பட்ட நோய்கள்',
    chronicDesc: 'நீரிழிவு நோய், உயர் இரத்த அழுத்தம் 및 நீண்ட கால உடல்நலப் பிரச்சினைகளுக்கு முழுமையான கவனிப்பு.',
    herbalFormTitle: 'மூலிகை சூத்திரங்கள்',
    herbalFormDesc: '7-தலைமுறை குடும்ப பாரம்பரிய முறையைப் பின்பற்றி தயாரிக்கப்பட்ட உண்மையான சித்த மருந்துகள்.',
    whyChooseClinic: 'ஏன் எங்கள் கிளினிக்கை தேர்வு செய்ய வேண்டும்?',
    safeNatural: 'பாதுகாப்பானது & இயற்கையானது',
    safeNaturalDesc: 'தீங்கு விளைவிக்கும் பக்க விளைவுகள் இல்லாத 100% மூலிகை மருந்துகள்',
    sevenGens: '7 தலைமுறைகள்',
    sevenGensDesc: 'ஏழு தலைமுறைகளாக கடத்தப்பட்ட பாரம்பரிய அறிவு',
    rootCure: 'மூல காரண தீர்வு',
    rootCureDesc: 'நாங்கள் அறிகுறிகளை மட்டும் குணப்படுத்தாமல், மூல காரணத்தை குணப்படுத்துகிறோம்',
    expertDoc: 'நிபுணர் மருத்துவர்',
    expertDocDesc: 'பல தசாப்த கால அனுபவம் கொண்ட தகுதி வாய்ந்த சித்த மருத்துவர்',
    reachUs: 'எங்களை அடையுங்கள்',
    contactInfo: 'தொடர்பு விவரங்கள்',
    tapToCall: 'அழைக்க தட்டவும்',
    email: 'மின்னஞ்சல்',
    sendEmail: 'மின்னஞ்சல் அனுப்புக',
    getDirections: 'வழித்தடம் அறிய',
    findUsMap: 'வரைபடத்தில் எங்களை காணுங்கள்',
    ourLoc: 'எங்கள் இருப்பிடம்',
    clinicAddr: 'கிளினிக் முகவரி',
    startHealing: 'இன்றே உங்கள் குணப்படுத்தும் பயணத்தைத் தொடங்குங்கள்',
    healingExp: 'பாரம்பரிய சித்த மருத்துவத்தின் ஆற்றலை அனுபவியுங்கள். எங்கள் மருத்துவர் திங்கள்-சனி, காலை 9 மணி முதல் இரவு 7 மணி வரை கிடைப்பார். நேரில் அல்லது வாட்ஸ்அப் மூலம் ஆலோசனையைப் பதிவு செய்யுங்கள்.',
    chatOnWhatsapp: 'வாட்ஸ்அப்பில் உரையாடுங்கள்',
    bookEConsult: 'மின் ஆலோசனை பதிவு செய்யுங்கள்',
    // ── Shipping & Delivery Extra ─────────────────────────────────────────────
    shippingHeroTag: 'இந்தியா முழுவதும் மற்றும் உலகம் முழுவதும் ஆயுர்வேத மற்றும் சித்த மருந்துகளின் வேகமான, பாதுகாப்பான மற்றும் நம்பகமான டெலிவரி.',
    sameDayDispatch: 'ஒரே நாளில் அனுப்புதல்',
    ordersBefore2PM: 'மதியம் 2 மணிக்கு முன் ஆர்டர்கள்',
    liveTracking: 'நேரடி கண்காணிப்பு',
    viaSMSWhatsapp: 'எஸ்எம்எஸ் மற்றும் வாட்ஸ்அப் வழியாக',
    safePackaging: 'பாதுகாப்பான பேக்கேஜிங்',
    tamperProofEco: 'பாதுகாப்பான மற்றும் சூழல் நட்பு பேக்கேஜிங்',
    howOrderTravels: 'உங்கள் ஆர்டர் எவ்வாறு பயணிக்கிறது',
    orderJourneySub: 'எங்கள் கிடங்கில் இருந்து உங்கள் வீட்டு வாசல் வரை — ஒவ்வொரு அடியும் கண்காணிக்கப்படுகிறது.',
    orderPlacedStep: 'ஆர்டர் செய்யப்பட்டது',
    orderPlacedDesc: 'உங்கள் ஆர்டர் உறுதி செய்யப்பட்டு பணம் பெறப்பட்டது.',
    qualityCheckStep: 'தரம் சரிபார்ப்பு',
    qualityCheckDesc: 'பொருட்கள் சரிபார்க்கப்பட்டு கவனமாக பேக் செய்யப்படுகின்றன.',
    dispatchedStep: 'அனுப்பப்பட்டது',
    dispatchedDesc: 'எங்கள் தளவாட பங்குதாரரிடம் ஒப்படைக்கப்பட்டது.',
    inTransitStep: 'பயணத்தில்',
    inTransitDesc: 'கண்காணிப்பு தகவல்கள் உங்கள் மின்னஞ்சல்/வாட்ஸ்அப்பிற்கு அனுப்பப்படும்.',
    deliveredStep: 'டெலிவரி செய்யப்பட்டது',
    deliveredDesc: 'பேக்கேஜ் உங்கள் வீட்டு வாசலில் டெலிவரி செய்யப்பட்டது.',
    ourShippingPolicies: 'எங்கள் கப்பல் கொள்கைகள்',
    shippingPoliciesSub: 'நீங்கள் ஆர்டர் செய்வதற்கு முன் நீங்கள் தெரிந்து கொள்ள வேண்டிய அனைத்தும்.',
    domesticShippingTitle: 'உள்நாட்டு கப்பல் (இந்தியா)',
    standardDelivery: 'சாதாரண டெலிவரி: இந்தியா முழுவதும் 5-7 வேலை நாட்கள்',
    expressDelivery: 'விரைவான டெலிவரி: 2-3 வேலை நாட்கள் (நகரங்கள்)',
    freeShippingAbove900: '₹900-க்கு மேல் ஆர்டர்களில் இலவச கப்பல் (தேர்ந்தெடுக்கப்பட்ட பொருட்கள்)',
    dispatchSameDay: 'மதியம் 2 மணிக்கு முன் வைக்கப்படும் ஆர்டர்கள் அதே நாளில் அனுப்பப்படும்',
    shipAllStates: 'நாங்கள் 28 மாநிலங்கள் மற்றும் 8 யூனியன் பிரதேசங்களுக்கு அனுப்புகிறோம்',
    intlShippingTitle: 'சர்வதேச கப்பல்',
    shipGlobal: 'உலகம் முழுவதும் 50+ நாடுகளுக்கு அனுப்புகிறோம்',
    intlDeliveryTime: 'அனுப்பப்பட்ட பிறகு டெலிவரிக்கு 10-15 வேலை நாட்கள் ஆகும்',
    dutyResponsibility: 'சுங்க வரி மற்றும் வரிகள் வாங்குபவரின் பொறுப்பு',
    herbalRestricted: 'சில மூலிகை திரவங்கள் சுங்க விதிமுறைகளால் கட்டுப்படுத்தப்படலாம்',
    intlQueries: 'சர்வதேச கேள்விகளுக்கு, அழைக்கவும்: +91 96292 97111',
    pkgStandardsTitle: 'பேக்கேஜிங் தரநிலைகள்',
    ecoTamperPkg: 'அனைத்து பொருட்களும் சூழல் நட்பு, பாதுகாப்பான பேக்கேஜிங்கில் பேக் செய்யப்படுகின்றன',
    bubbleWrapPkg: 'திரவ மற்றும் கண்ணாடி பொருட்கள் ஒவ்வொன்றாக குமிழி உறையில் சுற்றப்படுகின்றன',
    invoiceIncluded: 'ஒவ்வொரு பேக்கேஜிலும் விலைப்பட்டியல் சேர்க்கப்பட்டுள்ளது',
    plainBoxPkg: 'வெளிப்புற பெட்டி ப்ளைனாக இருக்கும் — தனியுரிமைக்காக பிராண்ட் அடையாளங்கள் இல்லை',
    coldChainPkg: 'குளிர்-சங்கிலி பேக்கேஜிங் முக்கியமான மருந்துகளுக்கு கிடைக்கிறது',
    cancelAddressTitle: 'ரத்து மற்றும் முகவரி மாற்றங்கள்',
    cancelWithin2h: 'ஆர்டர் செய்த 2 மணி நேரத்திற்குள் ஆர்டர்களை ரத்து செய்யலாம்',
    addrWithin2h: '2 மணி நேரத்திற்குள் முகவரி மாற்றங்களைக் கோர வேண்டும்',
    prepaidRefund: 'முன்கூட்டியே செலுத்திய ஆர்டர்கள்: 5-7 வேலை நாட்களில் பணம் திரும்பப் பெறப்படும்',
    dispatchedNoCancel: 'அனுப்பப்பட்ட பிறகு, ரத்து செய்ய முடியாது',
    whatsappUrgent: 'அவசர மாற்றங்களுக்கு உடனடியாக வாட்ஸ்அப் மூலம் எங்களைத் தொடர்பு கொள்ளுங்கள்',
    faqTitle: 'அடிக்கடி கேட்கப்படும் கேள்விகள்',
    faqSub: 'பொதுவான கப்பல் கேள்விகளுக்கான பதில்கள்.',
    faqQ1: 'இந்தியாவுக்குள் டெலிவரி எவ்வளவு காலம் எடுக்கும்?',
    faqA1: 'சாதாரண டெலிவரிக்கு 5-7 வேலை நாட்கள் ஆகும். எக்ஸ்பிரஸ் டெலிவரிக்கு 2-3 வேலை நாட்கள் ஆகும். தொலைதூர/மலைப் பகுதிகளுக்கு கூடுதலாக 1-2 நாட்கள் ஆகலாம். மதியம் 2 மணிக்கு முன் வரும் ஆர்டர்கள் அதே நாளில் (திங்கள்-சனி) அனுப்பப்படும்.',
    faqQ2: 'இலவச ஷிப்பிங் உண்டா?',
    faqA2: 'ஆம்! ₹900-க்கு மேற்பட்ட அனைத்து ஆர்டர்களுக்கும் இலவச சாதாரண ஷிப்பிங்கை வழங்குகிறோம். இது தேர்ந்தெடுக்கப்பட்ட பொருட்களுக்கு பொருந்தும் மற்றும் இந்தியாவிற்குள் டெலிவரிக்கு மட்டுமே செல்லுபடியாகும்.',
    faqQ3: 'நீங்கள் சர்வதேச அளவில் டெலிவரி செய்கிறீர்களா?',
    faqA3: 'ஆம், நாங்கள் உலகம் முழுவதும் பெரும்பாலான நாடுகளுக்கு அனுப்புகிறோம். சர்வதேச ஷிப்பிங் கட்டணங்கள் சேருமிடம் மற்றும் பேக்கேஜ் எடையின் அடிப்படையில் செக்அவுட்டின் போது கணக்கிடப்படும். மதிப்பிடப்பட்ட டெலிவரி அனுப்பப்பட்ட 10-15 வேலை நாட்கள் ஆகும்.',
    faqQ4: 'எனது ஆர்டரை நான் எவ்வாறு கண்காணிப்பது?',
    faqA4: 'உங்கள் ஆர்டர் அனுப்பப்பட்டதும், எஸ்எம்எஸ்/வாட்ஸ்அப் மற்றும் மின்னஞ்சல் வழியாக ஒரு கண்காணிப்பு எண்ணைப் பெறுவீர்கள். நீங்கள் கேரியரின் இணையதளத்தில் அல்லது எங்களை நேரடியாகத் தொடர்பு கொண்டு உங்கள் பேக்கேஜைக் கண்காணிக்கலாம்.',
    faqQ5: 'எனது பேக்கேஜ் சேதமடைந்தால் அல்லது தொலைந்து போனால் என்ன நடக்கும்?',
    faqA5: 'உங்கள் ஆர்டர் சேதமடைந்து வந்தாலோ அல்லது வழியில் தொலைந்து போனாலோ, எதிர்பார்க்கப்படும் டெலிவரி தேதியிலிருந்து 48 மணி நேரத்திற்குள் எங்களைத் தொடர்பு கொள்ளவும். விசாரணைக்குப் பிறகு நாங்கள் தயாரிப்பை மீண்டும் அனுப்புவோம் அல்லது முழு பணத்தைத் திரும்பப் பெறுவோம்.',
    faqQ6: 'ஆர்டர் செய்த பிறகு எனது டெலிவரி முகவரியை மாற்றலாமா?',
    faqA6: 'ஆர்டர் செய்த 2 மணி நேரத்திற்குள், அது அனுப்பப்படுவதற்கு முன்பு மட்டுமே முகவரி மாற்றங்களைச் செய்ய முடியும். மாற்றத்தைக் கோர உடனடியாகத் தொலைபேசி அல்லது வாட்ஸ்அப் மூலம் எங்களைத் தொடர்பு கொள்ளவும்.',
    faqQ7: 'அனுப்ப முடியாத பொருட்கள் ஏதேனும் உள்ளதா?',
    faqA7: 'சில திரவ மூலிகை தயாரிப்புகள் சில கூரியர்களால் அல்லது சர்வதேச சுங்க விதிமுறைகளால் கட்டுப்படுத்தப்படலாம். உங்கள் இருப்பிடத்திற்கு அனுப்ப முடியாத பொருள் ஏதேனும் இருந்தால், நாங்கள் உங்களுக்குத் தெரிவித்து முழுப் பணத்தையும் திரும்ப வழங்குவோம்.',
    faqQ8: 'தயாரிப்புகள் எவ்வாறு பேக் செய்யப்படுகின்றன?',
    faqA8: 'அனைத்து தயாரிப்புகளும் பாதுகாப்பான, சூழல் நட்பு பேக்கேஜிங்கில் பேக் செய்யப்படுகின்றன. கண்ணாடி பாட்டில்கள் போன்ற எளிதில் உடையக்கூடிய பொருட்கள் ஒவ்வொன்றாக குமிழி உறையில் (bubble-wrap) சுற்றப்படுகின்றன.',
    stillHaveQuestions: 'இன்னும் கேள்விகள் உள்ளதா?',
    supportTeamHours: 'எங்கள் குழு திங்கள் முதல் சனி வரை, காலை 10 மணி முதல் இரவு 7 மணி வரை கிடைக்கும். உடனடி ஆதரவுக்கு தொலைபேசி, மின்னஞ்சல் அல்லது வாட்ஸ்அப் மூலம் எங்களை அணுகவும்.',
    // ── Admin & Extra ────────────────────────────────────────────────────────
    adminDashboard: 'நிர்வாக டாஷ்போர்டு',
    addNewProduct: 'புதிய பொருளைச் சேர்',
    inventoryMgmt: 'சரக்கு மேலாண்மை',
    productNameLab: 'பொருளின் பெயர்',
    productDescLab: 'பொருள் விவரம்',
    productImgLab: 'பொருள் படம்',
    classification: 'வகைப்பாடு',
    categoryLab: 'வகை',
    brandLab: 'பிராண்ட்',
    formTypeLab: 'வடிவம் / வகை',
    ailmentsLab: 'நோய்கள் / குறிச்சொற்கள்',
    pricing: 'விலை',
    currentPriceLab: 'தற்போதைய விலை (₹)',
    mrpLab: 'எம்ஆர்பி (₹)',
    optional: 'விருப்பமானது',
    saveProduct: 'பொருளைச் சேமி',
    cancel: 'ரத்து செய்',
    saving: 'சேமிக்கப்படுகிறது...',
    secureCheckout: 'பாதுகாப்பான செக்அவுட் • விரைவான டெலிவரி',
    // ── Home & Categories ───────────────────────────────────────────────────
    heroSlide1Head: 'பண்டைய அறிவு,\nநவீன ஆரோக்கியம்',
    heroSlide1Sub: 'உண்மையான சித்த மற்றும் ஆயுர்வேத மருந்துகள் உங்கள் வீட்டு வாசலில் விநியோகிக்கப்படுகின்றன',
    heroSlide2Head: 'தூய்மையான. இயற்கை.\nஉண்மையான.',
    heroSlide2Sub: 'நம்பகமான பிராண்டுகளிலிருந்து இந்தியாவின் சிறந்த ஆயுர்வேத தயாரிப்புகளை வாங்கவும்',
    heroSlide3Head: 'இயற்கையாக குணமடையுங்கள்,\nமுழுமையாக வாழுங்கள்',
    heroSlide3Sub: 'ஒவ்வொரு தேவைக்கும் சான்றளிக்கப்பட்ட ஆயுர்வேத மருந்துகள்',
    catSiddhar: 'சித்தர்',
    catClassical: 'பாரம்பரிய மருந்துகள்',
    catPersonalCare: 'தனிப்பட்ட பராமரிப்பு',
    catBrands: 'பிராண்டுகள்',
    catHealthNutrition: 'ஆரோக்கியம் மற்றும் ஊட்டச்சத்து',
    catGeneral: 'பொதுவானது',
    chatOnWhatsappTitle: 'வாட்ஸ்அப்பில் எங்களுடன் சேட் செய்யுங்கள்',
    // ── Personal Care ────────────────────────────────────────────────────────
    pcHeroMain: 'காலத்தால் அழியாத \n சித்த அழகு',
    pcHeroSub: '"உங்கள் உடல் ஒரு கோயில்; பண்டைய குணப்படுத்துபவர்களின் புனித ஞானத்துடன் அதை நடத்துங்கள்."',
    pcBuildRegimen: 'உங்கள் வழக்கத்தை உருவாக்குங்கள்',
    pcExploreAll: 'அனைத்தையும் ஆராயுங்கள்',
    pcPillarsHead: 'ஒளியின் மூன்று \n தூண்கள்',
    pcPillarsSub: 'சித்த மருத்துவம் தனிப்பட்ட பராமரிப்பை மூன்று நகைச்சுவைகளின் (முக்குற்றம்) உள் மற்றும் வெளிப்புற இணக்கமாக பார்க்கிறது.',
    pcPithamTitle: 'பித்தம்',
    pcPithamFocus: 'பிரகாசம் மற்றும் வெப்பம்',
    pcPithamDesc: 'பித்தத்தை சமநிலைப்படுத்துவது வீக்கம், உணர்திறன் மற்றும் சிவத்தல் ஆகியவற்றை சரிசெய்கிறது.',
    pcVadhamTitle: 'வாதம்',
    pcVadhamFocus: 'ஈரப்பதம் மற்றும் ஓட்டம்',
    pcVadhamDesc: 'வாதம் பராமரிப்பு வறட்சி, மெல்லிய முடி மற்றும் முன்கூட்டிய வயதானதைத் தடுக்கிறது.',
    pcKabamTitle: 'கபம்',
    pcKabamFocus: 'உறுதி மற்றும் எண்ணெய்',
    pcKabamDesc: 'கபம் சமநிலைப்படுத்துவது அதிகப்படியான எண்ணெயைக் கட்டுப்படுத்துகிறது மற்றும் சரும நெகிழ்ச்சியைப் பராமரிக்கிறது.',
    pcPersonalizedCare: 'தனிப்பயனாக்கப்பட்ட பராமரிப்பு',
    pcCraftRitual: 'உங்கள் சடங்கை உருவாக்குங்கள்',
    pcCleanseTitle: 'சுத்தப்படுத்து',
    pcCleanseSub: 'நச்சுகளை நீக்கு',
    pcCleanseDesc: 'இயற்கை எண்ணெய்களை நீக்காமல் சருமத்தைச் சுத்தப்படுத்தும் பண்டைய கலவைகள்.',
    pcNourishTitle: 'ஊட்டு',
    pcNourishSub: 'ஆழ்ந்த ஈரப்பதம்',
    pcNourishDesc: 'செல் நிலை மீட்டெடுப்பிற்காக புனித எண்ணெய்கள் மற்றும் மூலிகை செறிவூட்டப்பட்ட சீரம்கள்.',
    pcHealTitle: 'குணப்படுத்து',
    pcHealSub: 'இலக்கு பராமரிப்பு',
    pcHealDesc: 'முகப்பரு, நிறமி மற்றும் முடி ஆரோக்கியத்திற்கான குறிப்பிட்ட சூத்திரங்கள்.',
    pcProtectTitle: 'பாதுகாப்பு',
    pcProtectSub: 'தினசரி கவசம்',
    pcProtectDesc: 'மாசு மற்றும் ஆக்சிஜனேற்றத்திலிருந்து பாதுகாக்கும் இலகுரக தடைகள்.',
    pcOnlyFromEarth: 'பூமியிலிருந்து \n மட்டுமே',
    pcNeemTurmeric: 'வேம்பு மற்றும் மஞ்சள்',
    pcGoldenHealers: '"கிழக்கின் தங்க குணப்படுத்துபவர்கள்"',
    pcHeritage: 'தோற்றம்.\n1994\nபாரம்பரியம்',
    pcSacredSourcing: 'புனித ஆதாரம்',
    pcSacredSourcingDesc: 'பண்டைய சித்த கையெழுத்துப் பிரதிகளில் பரிந்துரைக்கப்பட்டபடி, அவற்றின் ஜோதிட ஆற்றலின் உச்சத்தில் நாம் மூலிகைகளை பறிக்கிறோம்.',
    pcSlowExtraction: 'மெதுவான பிரித்தெடுத்தல்',
    pcSlowExtractionDesc: 'வெப்பம் இல்லை. இரசாயனங்கள் இல்லை. நமது தாவரங்களின் குணப்படுத்தும் சாரத்தைப் பிரித்தெடுக்க சூரியனும் நேரமும் மட்டுமே பயன்படுத்தப்படுகின்றன.',
    pcPurityCertified: 'தூய்மை சான்றளிக்கப்பட்டது',
    pcPurityCertifiedDesc: 'ஒவ்வொரு தொகுப்பும் பாராபென்கள், சல்பேட்டுகள் மற்றும் செயற்கை நறுமணங்கள் 100% இல்லாதவை என சோதிக்கப்படுகிறது.',
    pcBelovedModern: 'நவீன பயனர்களால் \n விரும்பப்படுகிறது',
    pcBelovedSub: 'இன்றைய நகர்ப்புற வாழ்க்கை முறையின் தேவைகளைப் பூர்த்தி செய்யும் பண்டைய தீர்வுகள்.',
    pcVoicesWellness: 'ஆரோக்கியத்தின் குரல்கள்',
    pcVoicesSub: 'சித்த ஞானம் நமது உலகளாவிய சமூகத்தின் வாழ்க்கையை எவ்வாறு மாற்றியுள்ளது.',
    pcVerifiedPurchase: 'சரிபார்க்கப்பட்ட கொள்முதல்',
    pcStartJourney: 'உங்கள் பயணத்தைத் தொடங்குங்கள்',
    pcBookFreeConsult: 'இலவச ஆலோசனை பதிவு செய்யுங்கள்',
    pcBrowseRituals: 'சடங்குகளை உலாவுங்கள்',
  },
};

const LangContext = createContext();

export const LangProvider = ({ children }) => {
  const [lang, setLang] = useState('en');
  const t = (key) => translations[lang][key] || key;
  const toggleLang = () => setLang(prev => prev === 'en' ? 'ta' : 'en');
  return (
    <LangContext.Provider value={{ lang, t, toggleLang }}>
      {children}
    </LangContext.Provider>
  );
};

export const useLang = () => useContext(LangContext);
