import React, { createContext, useContext, useState } from 'react';

const translations = {
  en: {
    // ── Nav / Global ──────────────────────────────────────────────────────────
    home: 'HOME',
    aboutUs: 'ABOUT US',
    siddhar: 'SIDDHAR',
    collections: 'COLLECTIONS',
    wishlist: 'WISHLIST',
    login: 'LOGIN',
    createAccount: 'CREATE AN ACCOUNT',
    cart: 'CART',
    switchLang: 'தமிழ்',
    orderOnline: 'Order Online or Call Us',
    freeShipping: 'FREE Shipping',
    onOrderAbove: 'ON ORDER ABOVE ₹900',
    onlySelected: '(Only On Selected Items)',
    searchPlaceholder: 'Search',
    signIn: 'Sign In',
    myAccount: 'My Account',
    // ── Footer ────────────────────────────────────────────────────────────────
    footerTagline: 'Authentic Ayurvedic & Siddha medicines delivered to your door.',
    informations: 'Informations',
    whatIsSiddhar: 'What Is Siddhar?',
    siddharWellness: 'Siddhar Wellness',
    search: 'Search',
    privacyPolicy: 'Privacy Policy',
    termsConditions: 'Terms & Conditions',
    sitemap: 'Sitemap',
    customerServices: 'Customer Services',
    contactUs: 'Contact Us',
    internationalShipping: 'International Shipping',
    returnsRefunds: 'Returns & Refunds',
    shippingDelivery: 'Shipping & Delivery',
    quickShop: 'Quick Shop',
    createAnAccount: 'Create an Account',
    stayConnected: 'Stay Connected',
    allRightsReserved: 'All Rights Reserved.',
    termsOfService: 'Terms of Service',
    refundPolicy: 'Refund Policy',
    // ── Home ──────────────────────────────────────────────────────────────────
    shopNow: 'Shop Now',
    bookConsultation: 'Book Consultation',
    buyAyurvedic: "Buy Ayurvedic Medicine Online from India's Largest Siddha Shopping Store",
    buyAyurvedicSub: 'Vel Siddhar Arakkattalai sells all kinds of Ayurvedic & Siddha medicines from top brands like Kottakkal Arya Vaidya Sala, Vaidyaratnam, AVP, Kerala Ayurveda, Himalaya, Dabur & more.',
    exploreAllProducts: 'Explore All Products',
    hundredNaturalFeat: '100% Natural',
    hundredNaturalDesc: 'All products are pure, natural, and free from harmful chemicals.',
    fastDelivery: 'Fast Delivery',
    fastDeliveryDesc: 'Free shipping on orders above ₹900. Quick and safe packaging.',
    trustedQuality: 'Trusted Quality',
    trustedQualityDesc: 'Sourced from certified Ayurvedic manufacturers across India.',
    certifiedProducts: 'Certified Products',
    certifiedProductsDesc: 'All medicines are GMP certified and clinically validated.',
    topSelling: 'Top Selling Ayurvedic Medicines',
    exploreMore: 'Explore our best-rated Ayurvedic & Siddha products',
    addToCartBtn: 'Add to Cart',
    shopByCategory: 'Shop by Category',
    shopByCategorySub: 'Find the perfect Ayurvedic solution for your needs',
    naturalHealthcare: 'Natural Healthcare with Ayurveda & Siddha',
    naturalHealthcareSub: 'Ayurveda, an ancient tradition of medicine in India, is focused on the idea that \'Prevention is better than cure.\' Siddha medicine, derived from Tamil tradition, complements Ayurveda with time-tested formulations for holistic wellness.',
    naturalHealthcareSub2: 'At Vel Siddhar Arakkattalai, we bring you the finest authentic products from India\'s most trusted Ayurvedic and Siddha medicine brands — all at your fingertips with fast, secure delivery.',
    learnAboutSiddhar: 'Learn About Siddhar',
    browseProducts: 'Browse Products',
    // ── Collections / Product ─────────────────────────────────────────────────
    allCollections: 'All Collections',
    discoverRange: 'Discover our authentic range of natural remedies and personal care products.',
    filterByCategory: 'Filter by Category',
    priceRange: 'Price Range',
    allPrices: 'All Prices',
    under100: 'Under ₹100',
    between100and500: '₹100 - ₹500',
    between500and1000: '₹500 - ₹1000',
    over1000: 'Over ₹1000',
    sortBy: 'Sort by',
    defaultSort: 'Default',
    priceLowHigh: 'Price: Low to High',
    priceHighLow: 'Price: High to Low',
    filters: 'Filters',
    results: 'results',
    noProducts: 'No products found matching your criteria.',
    clearFilters: 'Clear Filters',
    // ── Product Detail ────────────────────────────────────────────────────────
    back: 'Back',
    inclusiveTaxes: '(Inclusive of taxes)',
    inStock: 'Availability: In Stock',
    gmpCertified: 'GMP Certified',
    freeShippingAbove: 'Free shipping above ₹900',
    addedToCart: 'Added to Cart!',
    addedToWishlist: 'Added to Wishlist!',
    addToWishlist: 'Add to Wishlist',
    inWishlist: 'In Wishlist',
    addToCart: 'ADD TO CART',
    productDetails: 'Product Details',
    keyBenefits: 'Key Benefits',
    policies: 'Policies',
    disclaimer: 'Disclaimer',
    relatedProducts: 'Related Products',
    reviews: 'reviews',
    exchangeReturn: 'Exchange or Return within 7 days of delivery.',
    freeShippingPolicy: 'Free shipping on orders above ₹900.',
    internationalCall: 'For international shipping, call: +91 96292 97111.',
    disclaimerText: 'Results may vary from person to person. This product is not intended to diagnose, treat, cure or prevent any disease. Consult an Ayurvedic practitioner before use if you have any medical conditions or are pregnant/nursing.',
    benefitNatural: '100% natural ingredients — free from artificial additives',
    benefitClassical: 'Prepared using classical Ayurvedic methods',
    benefitGMP: 'GMP certified manufacturing facility',
    benefitSafe: 'Safe for regular use under guidance',
    benefitHolistic: 'Supports holistic health and wellness',
    // ── Cart ─────────────────────────────────────────────────────────────────
    yourCart: 'Your Cart',
    cartEmpty: 'Your Cart is Empty',
    cartEmptySub: 'Looks like you haven\'t added anything to your cart yet.',
    continueShopping: 'Continue Shopping',
    product: 'PRODUCT',
    price: 'PRICE',
    quantity: 'QUANTITY',
    total: 'TOTAL',
    action: 'ACTION',
    subtotal: 'Subtotal',
    shipping: 'Shipping',
    free: 'FREE',
    grandTotal: 'Grand Total',
    proceedCheckout: 'Proceed to Checkout',
    remove: 'Remove',
    // ── Checkout ──────────────────────────────────────────────────────────────
    checkout: 'Checkout',
    shippingInfo: 'Shipping Information',
    firstName: 'First Name',
    lastName: 'Last Name',
    email: 'Email Address',
    phone: 'Phone Number',
    address: 'Address',
    city: 'City',
    state: 'State',
    pincode: 'Pincode',
    orderSummary: 'Order Summary',
    placeOrder: 'Place Order',
    // ── Payment ───────────────────────────────────────────────────────────────
    payment: 'Payment',
    selectPayment: 'Select Payment Method',
    upi: 'UPI',
    card: 'Credit / Debit Card',
    cod: 'Cash on Delivery',
    payNow: 'Pay Now',
    orderSuccess: 'Payment Successful!',
    orderSuccessMsg: 'Your order has been placed. Thank you!',
    backHome: 'Back to Home',
    orderPlaced: 'Order Placed Successfully!',
    thankYou: 'Thank you for shopping with us.',
    orderId: 'Order ID',
    upiId: 'Enter UPI ID (e.g. name@upi)',
    cardNumber: 'Card Number',
    expiry: 'Expiry (MM/YY)',
    cvv: 'CVV',
    upiVerify: 'Verify & Pay',
    // ── Wishlist ──────────────────────────────────────────────────────────────
    yourWishlist: 'Your Wishlist',
    emptyWishlist: 'Your wishlist is empty.',
    emptyWishlistSub: 'Save products you love and come back to them anytime.',
    removeWishlist: 'Remove',
    moveToCart: 'Move to Cart',
    // ── Login ─────────────────────────────────────────────────────────────────
    welcomeBack: 'Welcome Back',
    loginSubtitle: 'Please enter your details to access your account.',
    username: 'Username',
    password: 'Password',
    enterUsername: 'Enter your username',
    enterPassword: 'Enter your password',
    rememberMe: 'Remember for 30 days',
    forgotPassword: 'Forgot password?',
    signingIn: 'Authenticating...',
    signInBtn: 'Sign In',
    noAccount: "Don't have an account?",
    signUpToday: 'Sign up today',
    // ── Signup ────────────────────────────────────────────────────────────────
    createYourAccount: 'Create Your Account',
    signupSubtitle: 'Join us and discover authentic Ayurvedic wellness.',
    fullName: 'Full Name',
    enterFullName: 'Enter your full name',
    confirmPassword: 'Confirm Password',
    confirmPasswordPlaceholder: 'Re-enter your password',
    createAccountBtn: 'Create Account',
    alreadyHaveAccount: 'Already have an account?',
    signInLink: 'Sign in here',
    // ── Profile ───────────────────────────────────────────────────────────────
    myProfile: 'My Profile',
    accountInfo: 'Account Information',
    orderHistory: 'Order History',
    noOrders: 'No orders placed yet.',
    logout: 'Logout',
    // ── About Us ──────────────────────────────────────────────────────────────
    ourHeritage: 'Our Heritage',
    heritageText: 'We bring to you the traditional wisdom of Ayurveda combined with modern science. Our mission is to provide 100% natural, safe, and effective Ayurvedic medicines and personal care products. For over three decades, we have been a trusted name in healthcare, focusing on holistic healing and well-being.',
    qualityFirst: 'Quality First',
    qualityText: 'Every product in our store is carefully curated. We partner with top Ayurvedic brands like Kottakkal Arya Vaidya Sala and others to ensure authenticity. From farm to shelf, we ensure strict hygiene and quality protocols.',
    expertDoctors: 'Expert Ayurvedic Doctors',
    expertDoctorsSub: 'Consult with our specialists for a healthier life.',
    // ── E-Consultation ────────────────────────────────────────────────────────
    eConsultTitle: 'E-Consultation (Book Now)',
    eConsultSub: 'Get personalized health advice from expert Ayurvedic physicians entirely online.',
    bookingConfirmed: 'Booking Confirmed!',
    bookingConfirmedMsg: 'We have sent the consultation link to your email. Our doctor will be with you shortly.',
    bookAppointment: 'Book an Appointment',
    fillDetails: 'Fill out details below',
    fullNameLabel: 'Full Name',
    phoneLabel: 'Phone Number',
    preferredDate: 'Preferred Date',
    preferredTime: 'Preferred Time',
    selectSlot: 'Select a slot',
    morning: 'Morning (10 AM - 12 PM)',
    afternoon: 'Afternoon (2 PM - 5 PM)',
    evening: 'Evening (6 PM - 8 PM)',
    healthIssue: 'Describe Your Health Issue',
    healthIssuePlaceholder: 'e.g. Seeking consultation for joint pain and fatigue...',
    confirmBooking: 'Confirm Booking',
    // ── Personal Care ─────────────────────────────────────────────────────────
    personalCare: 'Personal Care',
    theSiddhaWay: 'The Siddha Way',
    naturalAndAuthentic: 'Natural & Authentic',
    shopPersonalCare: 'Shop Personal Care',
    freeSkinConsultation: 'Free Skin Consultation',
    browseByCategory: 'Browse by Category',
    findPerfectCare: 'Find the perfect care for every part of you',
    ourProducts: 'Our Products',
    authenticProducts: 'Authentic Siddha personal care, naturally crafted',
    searchProducts: 'Search products...',
    viewAllPersonalCare: 'View All Personal Care Products',
    whyChoosePersonalCare: 'Why Choose Our Personal Care?',
    siddhaAdvantage: 'The Siddha advantage for your everyday care routine',
    wellnessTips: 'Siddha Wellness Tips',
    ancientRoutines: 'Ancient routines for modern glowing skin & healthy hair',
    customersSay: 'What Our Customers Say',
    realResults: 'Real results from real people with our natural products',
    naturalJourney: 'Start Your Natural Skincare Journey Today',
    notSureConsult: 'Not sure what\'s right for your skin or hair? Book a free online consultation with our Siddha experts.',
    bookFreeConsultation: 'Book Free Consultation',
    faceCareCat: 'Face Care',
    hairCareCat: 'Hair Care',
    bodyCareCat: 'Body Care',
    herbalOilsCat: 'Herbal Oils',
    faceCareDesc: 'Cleansers, face packs, serums & moisturisers',
    hairCareDesc: 'Oils, shampoos, conditioners & hair masks',
    bodyCareDesc: 'Scrubs, lotions, bath oils & soaps',
    herbalOilsDesc: 'Medicated oils for skin, scalp & massage',
    fivePlusProd: '50+ Personal Care Products',
    hundredNatural: '100% Natural Ingredients',
    happyCustomers: '2500+ Happy Customers',
    yearsHeritage: '30+ Years of Heritage',
    allPersonalCare: 'All Personal Care',
    aboutSection: 'About',
    ayurvedicTips: 'Ayurvedic Tips',
    recommendedProducts: 'Recommended Products',
    notSureWhatsRight: "Not sure what's right for you?",
    getFreeConsultation: 'Get a free personalised consultation from our Siddha experts.',
    noProductsYet: 'No products available yet. Check back soon!',
    browseAllCollections: 'Browse All Collections',
    group1: 'Ayurvedic Medicine For',
    group2: 'Ayurvedic Products For',
    group3: 'Digestive & Metabolic Care',
    // ── 404 ──────────────────────────────────────────────────────────────────
    pageNotFound: 'Page Not Found',
    pageNotFoundSub: 'The page you are looking for doesn\'t exist or has been moved.',
    goHome: 'Go to Homepage',
    // ── Navbar & Footer & Profile Extra ───────────────────────────────────────
    brandVelSiddhar: 'Vel Siddhar',
    brandArakkattalai: 'Arakkattalai',
    address: 'New No.19, Old No.61, 27th Street, L-Block, Anna nagar East, Chennai - 600 102. India',
    emailId: 'sales@velsiddhararakkattalai.com',
    phoneNum: '(044) 4859 9296',
    admin: 'ADMIN',
    myOrders: 'My Orders',
    healthNutrition: 'Health & Nutrition',
    companyProfileTitle: 'Company Profile',
    heritageAndReviews: 'Heritage & Reviews',
    coughAndCold: 'Cough and Cold',
    fever: 'Fever',
    migraine: 'Migraine',
    sinus: 'Sinus',
    bodyCare: 'Body Care',
    faceCare: 'Face Care',
    ayurvedicHairOil: 'Ayurvedic Hair Oil',
    skinBeautyCare: 'Skin & Beauty Care',
    constipation: 'Constipation',
    diabetesControl: 'Diabetes / Sugar Control',
    digestion: 'Digestion',
    gastroHealth: 'Gastro Health & Acidity',
    obesity: 'Obesity',
    pilesHemorrhoid: 'Piles & Hemorrhoid',
    cpHeading: 'Vel Siddhar Arakkattalai - Company Profile',
    cpSubheading: 'One of the Best Online Ayurvedic Stores in India',
    cpP1: 'Looking for Ayurvedic medicines shouldn’t feel like a full-day task. Going from one shop to another, asking around, and still not finding what you need… it can honestly get frustrating. Most of us have faced that at some point.',
    cpP2: 'That’s exactly why Vel Siddhar Arakkattalai keeps things simple and easy. Instead of wasting time searching outside, you can just tell us what you’re looking for, and we’ll make sure it reaches your home. No running around, no confusion, no last-minute stress.',
    cpP3: 'Ayurveda is a natural way to take care of your health, helping your body and mind in a gentle and balanced way. Many people choose it because it is generally safe when taken properly and focuses on long-term wellness. Even people with sugar problems can use Ayurvedic support along with their regular medicines, with the right guidance and timing.',
    cpP4: 'Another good thing is that Ayurvedic treatments often focus on overall health, so they can help manage more than one issue at the same time. We also believe in giving back, which is why we have conducted more than four free medical camps and provided medicines to people in need.',
    cpP5: 'We focus on providing good quality products, delivering them on time, and making the whole process comfortable for you. Nothing complicated here—just a simple idea: helping you get the right medicines, at the right time, without all the extra effort.',
    exploreCollections: 'Explore Our Collections',
  },

  ta: {
    // ── Nav / Global ──────────────────────────────────────────────────────────
    home: 'முகப்பு',
    aboutUs: 'எங்களை பற்றி',
    siddhar: 'சித்தர்',
    collections: 'தொகுப்புகள்',
    wishlist: 'விருப்பப் பட்டியல்',
    login: 'உள்நுழைவு',
    createAccount: 'கணக்கு உருவாக்கு',
    cart: 'வண்டி',
    switchLang: 'English',
    orderOnline: 'ஆன்லைனில் ஆர்டர் செய்யுங்கள் அல்லது அழைக்கவும்',
    freeShipping: 'இலவச கப்பல்',
    onOrderAbove: '₹900-க்கு மேல் ஆர்டரில்',
    onlySelected: '(தேர்ந்தெடுக்கப்பட்ட பொருட்களில் மட்டுமே)',
    searchPlaceholder: 'தேடு',
    signIn: 'உள்நுழை',
    myAccount: 'என் கணக்கு',
    // ── Footer ────────────────────────────────────────────────────────────────
    footerTagline: 'நம்பகமான ஆயுர்வேத & சித்த மருந்துகள் உங்கள் வீட்டிற்கு.',
    informations: 'தகவல்கள்',
    whatIsSiddhar: 'சித்தர் என்றால் என்ன?',
    siddharWellness: 'சித்தர் நலவாழ்வு',
    search: 'தேடு',
    privacyPolicy: 'தனியுரிமைக் கொள்கை',
    termsConditions: 'விதிமுறைகள் & நிபந்தனைகள்',
    sitemap: 'தள வரைபடம்',
    customerServices: 'வாடிக்கையாளர் சேவைகள்',
    contactUs: 'தொடர்பு கொள்ளுங்கள்',
    internationalShipping: 'சர்வதேச கப்பல்',
    returnsRefunds: 'திரும்பல் & திரும்பப் பெறுதல்',
    shippingDelivery: 'கப்பல் & டெலிவரி',
    quickShop: 'விரைவு கடை',
    createAnAccount: 'கணக்கு உருவாக்கு',
    stayConnected: 'தொடர்பில் இருங்கள்',
    allRightsReserved: 'அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை.',
    termsOfService: 'சேவை விதிமுறைகள்',
    refundPolicy: 'திரும்பப் பெறும் கொள்கை',
    // ── Home ──────────────────────────────────────────────────────────────────
    shopNow: 'இப்போதே வாங்கவும்',
    bookConsultation: 'ஆலோசனை பதிவு',
    buyAyurvedic: 'இந்தியாவின் மிகப்பெரிய சித்த கடையில் இருந்து ஆன்லைனில் ஆயுர்வேத மருந்துகள் வாங்கவும்',
    buyAyurvedicSub: 'வேல் சித்தர் அரக்கட்டளை கொட்டக்கல் ஆர்யா வைத்ய சாலா, வைத்யரத்னம், AVP, கேரள ஆயுர்வேதம், இமாலயா, டாபர் மற்றும் பலவற்றிலிருந்து அனைத்து வகையான ஆயுர்வேத மற்றும் சித்த மருந்துகளை விற்கிறது.',
    exploreAllProducts: 'அனைத்து பொருட்களையும் ஆராயுங்கள்',
    hundredNaturalFeat: '100% இயற்கை',
    hundredNaturalDesc: 'அனைத்து பொருட்களும் தூய்மையான, இயற்கையான மற்றும் தீங்கான இரசாயனங்கள் இல்லாதவை.',
    fastDelivery: 'விரைவு டெலிவரி',
    fastDeliveryDesc: '₹900-க்கு மேல் ஆர்டரில் இலவச கப்பல். விரைவான மற்றும் பாதுகாப்பான பேக்கேஜிங்.',
    trustedQuality: 'நம்பகமான தரம்',
    trustedQualityDesc: 'இந்தியா முழுவதும் சான்றளிக்கப்பட்ட ஆயுர்வேத உற்பத்தியாளர்களிடமிருந்து பெறப்படுகிறது.',
    certifiedProducts: 'சான்றளிக்கப்பட்ட பொருட்கள்',
    certifiedProductsDesc: 'அனைத்து மருந்துகளும் GMP சான்றளிக்கப்பட்டு மருத்துவ ரீதியாக சரிபார்க்கப்பட்டவை.',
    topSelling: 'சிறந்த விற்பனை ஆயுர்வேத மருந்துகள்',
    exploreMore: 'எங்கள் சிறந்த மதிப்பீட்டு ஆயுர்வேத & சித்த பொருட்களை ஆராயுங்கள்',
    addToCartBtn: 'வண்டியில் சேர்',
    shopByCategory: 'வகையின்படி வாங்கவும்',
    shopByCategorySub: 'உங்கள் தேவைக்கு சரியான ஆயுர்வேத தீர்வை கண்டறியுங்கள்',
    naturalHealthcare: 'ஆயுர்வேதம் & சித்தத்துடன் இயற்கை சுகாதாரம்',
    naturalHealthcareSub: 'இந்தியாவின் ஒரு பழங்கால மருத்துவ மரபான ஆயுர்வேதம் "தடுப்பு குணப்படுத்துவதை விட சிறந்தது" என்ற கருத்தை கையாளுகிறது. தமிழ் மரபிலிருந்து வந்த சித்த மருத்துவம் ஆயுர்வேதத்தை முழுமையான நலனுக்கான கால-சோதிக்கப்பட்ட சூத்திரங்களுடன் நிறைவு செய்கிறது.',
    naturalHealthcareSub2: 'வேல் சித்தர் அரக்கட்டளையில், இந்தியாவின் மிகவும் நம்பகமான ஆயுர்வேத மற்றும் சித்த மருந்து பிராண்டுகளிலிருந்து சிறந்த நம்பகமான பொருட்களை வேகமான, பாதுகாப்பான டெலிவரியுடன் உங்கள் விரல் நுனியில் கொண்டு வருகிறோம்.',
    learnAboutSiddhar: 'சித்தரை பற்றி அறியுங்கள்',
    browseProducts: 'பொருட்களை உலாவுங்கள்',
    // ── Collections / Product ─────────────────────────────────────────────────
    allCollections: 'அனைத்து தொகுப்புகள்',
    discoverRange: 'எங்கள் நம்பகமான இயற்கை மருந்துகள் மற்றும் தனிப்பட்ட பராமரிப்பு பொருட்களை கண்டறியுங்கள்.',
    filterByCategory: 'வகையின்படி வடிகட்டு',
    priceRange: 'விலை வரம்பு',
    allPrices: 'அனைத்து விலைகளும்',
    under100: '₹100-க்கு கீழ்',
    between100and500: '₹100 - ₹500',
    between500and1000: '₹500 - ₹1000',
    over1000: '₹1000-க்கு மேல்',
    sortBy: 'வரிசைப்படுத்து',
    defaultSort: 'இயல்பு',
    priceLowHigh: 'விலை: குறைவிலிருந்து அதிகம்',
    priceHighLow: 'விலை: அதிகத்திலிருந்து குறைவு',
    filters: 'வடிகட்டிகள்',
    results: 'முடிவுகள்',
    noProducts: 'உங்கள் தேர்வுக்கு பொருந்தும் பொருட்கள் எதுவும் இல்லை.',
    clearFilters: 'வடிகட்டிகளை அழி',
    // ── Product Detail ────────────────────────────────────────────────────────
    back: 'பின்செல்',
    inclusiveTaxes: '(வரிகள் உட்பட)',
    inStock: 'கிடைக்கும் தன்மை: கையிருப்பில் உள்ளது',
    gmpCertified: 'GMP சான்றளிக்கப்பட்டது',
    freeShippingAbove: '₹900-க்கு மேல் இலவச கப்பல்',
    addedToCart: 'வண்டியில் சேர்க்கப்பட்டது!',
    addedToWishlist: 'விருப்பப் பட்டியலில் சேர்க்கப்பட்டது!',
    addToWishlist: 'விருப்பப் பட்டியலில் சேர்',
    inWishlist: 'விருப்பப் பட்டியலில் உள்ளது',
    addToCart: 'வண்டியில் சேர்',
    productDetails: 'பொருள் விவரங்கள்',
    keyBenefits: 'முக்கிய நன்மைகள்',
    policies: 'கொள்கைகள்',
    disclaimer: 'மறுப்பு',
    relatedProducts: 'தொடர்பான பொருட்கள்',
    reviews: 'விமர்சனங்கள்',
    exchangeReturn: 'டெலிவரி செய்த 7 நாட்களுக்குள் மாற்று அல்லது திரும்பு.',
    freeShippingPolicy: '₹900-க்கு மேல் ஆர்டரில் இலவச கப்பல்.',
    internationalCall: 'சர்வதேச கப்பலுக்கு அழைக்கவும்: +91 96292 97111.',
    disclaimerText: 'முடிவுகள் நபருக்கு நபர் மாறுபடலாம். இந்த பொருள் எந்த நோயையும் கண்டறிக்கவோ, சிகிச்சை செய்யவோ, குணப்படுத்தவோ அல்லது தடுக்கவோ நோக்கமாகவில்லை.',
    benefitNatural: '100% இயற்கை பொருட்கள் — செயற்கை சேர்க்கைகள் இல்லாதவை',
    benefitClassical: 'கிளாசிக்கல் ஆயுர்வேத முறைகளைப் பயன்படுத்தி தயாரிக்கப்பட்டது',
    benefitGMP: 'GMP சான்றளிக்கப்பட்ட உற்பத்தி வசதி',
    benefitSafe: 'வழிகாட்டுதலின் கீழ் வழக்கமான பயன்பாட்டிற்கு பாதுகாப்பானது',
    benefitHolistic: 'முழுமையான ஆரோக்கியம் மற்றும் நலனை ஆதரிக்கிறது',
    // ── Cart ─────────────────────────────────────────────────────────────────
    yourCart: 'உங்கள் வண்டி',
    cartEmpty: 'உங்கள் வண்டி காலியாக உள்ளது',
    cartEmptySub: 'நீங்கள் இன்னும் வண்டியில் எதுவும் சேர்க்கவில்லை.',
    continueShopping: 'ஷாப்பிங் தொடர்க',
    product: 'பொருள்',
    price: 'விலை',
    quantity: 'அளவு',
    total: 'மொத்தம்',
    action: 'செயல்',
    subtotal: 'இடைத்தொகை',
    shipping: 'கப்பல் கட்டணம்',
    free: 'இலவசம்',
    grandTotal: 'மொத்த தொகை',
    proceedCheckout: 'வாங்குவதற்கு தொடர்க',
    remove: 'நீக்கு',
    // ── Checkout ──────────────────────────────────────────────────────────────
    checkout: 'வாங்குதல்',
    shippingInfo: 'கப்பல் தகவல்',
    firstName: 'முதல் பெயர்',
    lastName: 'கடைசி பெயர்',
    email: 'மின்னஞ்சல் முகவரி',
    phone: 'தொலைபேசி எண்',
    address: 'முகவரி',
    city: 'நகரம்',
    state: 'மாநிலம்',
    pincode: 'அஞ்சல் குறியீடு',
    orderSummary: 'ஆர்டர் சுருக்கம்',
    placeOrder: 'ஆர்டர் வைக்கவும்',
    // ── Payment ───────────────────────────────────────────────────────────────
    payment: 'கட்டணம்',
    selectPayment: 'கட்டண முறையை தேர்ந்தெடுக்கவும்',
    upi: 'யூபிஐ',
    card: 'கிரெடிட் / டெபிட் கார்டு',
    cod: 'பணச் செலுத்தல் (COD)',
    payNow: 'இப்போது செலுத்துக',
    orderSuccess: 'கட்டணம் வெற்றிகரமாக செலுத்தப்பட்டது!',
    orderSuccessMsg: 'உங்கள் ஆர்டர் வைக்கப்பட்டது. நன்றி!',
    backHome: 'முகப்புக்கு திரும்பு',
    orderPlaced: 'ஆர்டர் வெற்றிகரமாக வைக்கப்பட்டது!',
    thankYou: 'எங்களிடம் கொள்முதல் செய்ததற்கு நன்றி.',
    orderId: 'ஆர்டர் ஐடி',
    upiId: 'UPI ID உள்ளிடவும் (எ.கா. name@upi)',
    cardNumber: 'கார்டு எண்',
    expiry: 'காலாவதி (MM/YY)',
    cvv: 'CVV',
    upiVerify: 'சரிபார்த்து செலுத்துக',
    // ── Wishlist ──────────────────────────────────────────────────────────────
    yourWishlist: 'உங்கள் விருப்பப் பட்டியல்',
    emptyWishlist: 'உங்கள் விருப்பப் பட்டியல் காலியாக உள்ளது.',
    emptyWishlistSub: 'நீங்கள் விரும்பும் பொருட்களை சேமித்து எப்போது வேண்டுமானாலும் திரும்பி வாருங்கள்.',
    removeWishlist: 'நீக்கு',
    moveToCart: 'வண்டிக்கு நகர்த்து',
    // ── Login ─────────────────────────────────────────────────────────────────
    welcomeBack: 'மீண்டும் வரவேற்கிறோம்',
    loginSubtitle: 'உங்கள் கணக்கை அணுக விவரங்களை உள்ளிடவும்.',
    username: 'பயனர் பெயர்',
    password: 'கடவுச்சொல்',
    enterUsername: 'உங்கள் பயனர் பெயரை உள்ளிடவும்',
    enterPassword: 'உங்கள் கடவுச்சொல்லை உள்ளிடவும்',
    rememberMe: '30 நாட்களுக்கு நினைவில் வை',
    forgotPassword: 'கடவுச்சொல் மறந்துவிட்டதா?',
    signingIn: 'உள்நுழைகிறோம்...',
    signInBtn: 'உள்நுழை',
    noAccount: 'கணக்கு இல்லையா?',
    signUpToday: 'இன்றே பதிவு செய்யுங்கள்',
    // ── Signup ────────────────────────────────────────────────────────────────
    createYourAccount: 'உங்கள் கணக்கை உருவாக்குங்கள்',
    signupSubtitle: 'எங்களுடன் இணைந்து நம்பகமான ஆயுர்வேத நலன் கண்டறியுங்கள்.',
    fullName: 'முழு பெயர்',
    enterFullName: 'உங்கள் முழு பெயரை உள்ளிடவும்',
    confirmPassword: 'கடவுச்சொல்லை உறுதிப்படுத்து',
    confirmPasswordPlaceholder: 'கடவுச்சொல்லை மீண்டும் உள்ளிடவும்',
    createAccountBtn: 'கணக்கு உருவாக்கு',
    alreadyHaveAccount: 'ஏற்கனவே கணக்கு உள்ளதா?',
    signInLink: 'இங்கே உள்நுழையுங்கள்',
    // ── Profile ───────────────────────────────────────────────────────────────
    myProfile: 'என் சுயவிவரம்',
    accountInfo: 'கணக்கு தகவல்',
    orderHistory: 'ஆர்டர் வரலாறு',
    noOrders: 'இன்னும் ஆர்டர்கள் எதுவும் இல்லை.',
    logout: 'வெளியேறு',
    // ── About Us ──────────────────────────────────────────────────────────────
    ourHeritage: 'எங்கள் மரபு',
    heritageText: 'நவீன அறிவியலுடன் இணைந்த ஆயுர்வேதத்தின் பாரம்பரிய ஞானத்தை உங்களுக்கு கொண்டு வருகிறோம். 100% இயற்கையான, பாதுகாப்பான மற்றும் பயனுள்ள ஆயுர்வேத மருந்துகளை வழங்குவதே எங்கள் நோக்கம்.',
    qualityFirst: 'தரம் முதலில்',
    qualityText: 'எங்கள் கடையில் உள்ள ஒவ்வொரு பொருளும் கவனமாக தேர்ந்தெடுக்கப்படுகிறது. கொட்டக்கல் ஆர்யா வைத்ய சாலா போன்ற சிறந்த ஆயுர்வேத பிராண்டுகளுடன் பணியாற்றுகிறோம்.',
    expertDoctors: 'நிபுணர் ஆயுர்வேத மருத்துவர்கள்',
    expertDoctorsSub: 'ஆரோக்கியமான வாழ்க்கைக்கு எங்கள் நிபுணர்களிடம் ஆலோசனை பெறுங்கள்.',
    // ── E-Consultation ────────────────────────────────────────────────────────
    eConsultTitle: 'மின் ஆலோசனை (இப்போதே பதிவு செய்யுங்கள்)',
    eConsultSub: 'நிபுணர் ஆயுர்வேத மருத்துவர்களிடமிருந்து ஆன்லைனில் தனிப்பட்ட ஆரோக்கிய ஆலோசனை பெறுங்கள்.',
    bookingConfirmed: 'பதிவு உறுதிப்படுத்தப்பட்டது!',
    bookingConfirmedMsg: 'ஆலோசனை இணைப்பை உங்கள் மின்னஞ்சலுக்கு அனுப்பியுள்ளோம். எங்கள் மருத்துவர் விரைவில் உங்களிடம் வருவார்.',
    bookAppointment: 'சந்திப்பு பதிவு செய்யுங்கள்',
    fillDetails: 'கீழே விவரங்களை பூர்த்தி செய்யுங்கள்',
    fullNameLabel: 'முழு பெயர்',
    phoneLabel: 'தொலைபேசி எண்',
    preferredDate: 'விரும்பிய தேதி',
    preferredTime: 'விரும்பிய நேரம்',
    selectSlot: 'ஒரு நேர இடத்தை தேர்ந்தெடுக்கவும்',
    morning: 'காலை (10 AM - 12 PM)',
    afternoon: 'மதியம் (2 PM - 5 PM)',
    evening: 'மாலை (6 PM - 8 PM)',
    healthIssue: 'உங்கள் உடல்நலப் பிரச்சினையை விளக்குங்கள்',
    healthIssuePlaceholder: 'எ.கா. மூட்டு வலி மற்றும் சோர்வுக்கு ஆலோசனை கோருகிறேன்...',
    confirmBooking: 'பதிவை உறுதிப்படுத்துங்கள்',
    // ── Personal Care ─────────────────────────────────────────────────────────
    personalCare: 'தனிப்பட்ட பராமரிப்பு',
    theSiddhaWay: 'சித்த வழியில்',
    naturalAndAuthentic: 'இயற்கை & நம்பகமான',
    shopPersonalCare: 'தனிப்பட்ட பராமரிப்பு வாங்கவும்',
    freeSkinConsultation: 'இலவச சரும ஆலோசனை',
    browseByCategory: 'வகையின்படி உலாவுங்கள்',
    findPerfectCare: 'உங்களுக்கு சரியான பராமரிப்பை கண்டறியுங்கள்',
    ourProducts: 'எங்கள் பொருட்கள்',
    authenticProducts: 'இயற்கையாக தயாரிக்கப்பட்ட சித்த தனிப்பட்ட பராமரிப்பு',
    searchProducts: 'பொருட்களை தேடுங்கள்...',
    viewAllPersonalCare: 'அனைத்து தனிப்பட்ட பராமரிப்பு பொருட்களையும் காண்க',
    whyChoosePersonalCare: 'ஏன் எங்கள் தனிப்பட்ட பராமரிப்பை தேர்ந்தெடுக்கணும்?',
    siddhaAdvantage: 'உங்கள் தினசரி பராமரிப்புக்கான சித்த சிறப்பு',
    wellnessTips: 'சித்த ஆரோக்கிய குறிப்புகள்',
    ancientRoutines: 'நவீன ஒளிரும் சருமத்திற்கான பழங்கால வழித்தடங்கள்',
    customersSay: 'வாடிக்கையாளர்கள் என்ன சொல்கிறார்கள்',
    realResults: 'இயற்கை பொருட்களால் உண்மையான முடிவுகள்',
    naturalJourney: 'இன்றே உங்கள் இயற்கை சரும பயணத்தை தொடங்குங்கள்',
    notSureConsult: 'உங்கள் சருமம் அல்லது முடிக்கு எது சரியானது என்று தெரியவில்லையா? சித்த நிபுணர்களிடம் இலவச ஆலோசனை பெறுங்கள்.',
    bookFreeConsultation: 'இலவச ஆலோசனை பதிவு செய்யுங்கள்',
    faceCareCat: 'சரும பராமரிப்பு',
    hairCareCat: 'முடி பராமரிப்பு',
    bodyCareCat: 'உடல் பராமரிப்பு',
    herbalOilsCat: 'மூலிகை எண்ணெய்கள்',
    faceCareDesc: 'சுத்தப்படுத்திகள், சரும பேக்குகள், சீரம் & மாய்சர்சர்',
    hairCareDesc: 'எண்ணெய்கள், ஷாம்பு, கண்டிஷனர் & முடி பேக்குகள்',
    bodyCareDesc: 'ஸ்க்ரப்புகள், லோஷன்கள், குளியல் எண்ணெய் & சோப்புகள்',
    herbalOilsDesc: 'சருமம், தலை & மசாஜுக்கான மருந்திட்ட எண்ணெய்கள்',
    fivePlusProd: '50+ தனிப்பட்ட பராமரிப்பு பொருட்கள்',
    hundredNatural: '100% இயற்கை பொருட்கள்',
    happyCustomers: '2500+ மகிழ்ச்சியான வாடிக்கையாளர்கள்',
    yearsHeritage: '30+ ஆண்டுகள் மரபு',
    allPersonalCare: 'அனைத்து தனிப்பட்ட பராமரிப்பு',
    aboutSection: 'பற்றி',
    ayurvedicTips: 'ஆயுர்வேத குறிப்புகள்',
    recommendedProducts: 'பரிந்துரைக்கப்பட்ட பொருட்கள்',
    notSureWhatsRight: 'எது சரியானது என்று தெரியவில்லையா?',
    getFreeConsultation: 'எங்கள் சித்த நிபுணர்களிடம் இலவச ஆலோசனை பெறுங்கள்.',
    noProductsYet: 'பொருட்கள் இன்னும் இல்லை. விரைவில் சரிபாருங்கள்!',
    browseAllCollections: 'அனைத்து தொகுப்புகளையும் உலாவுங்கள்',
    group1: 'ஆயுர்வேத மருத்துவம்',
    group2: 'ஆயுர்வேத பொருட்கள்',
    group3: 'செரிமான & வளர்சிதை மாற்ற பராமரிப்பு',
    // ── 404 ──────────────────────────────────────────────────────────────────
    pageNotFound: 'பக்கம் கண்டுபிடிக்கவில்லை',
    pageNotFoundSub: 'நீங்கள் தேடும் பக்கம் இல்லை அல்லது நகர்த்தப்பட்டுள்ளது.',
    goHome: 'முகப்பு பக்கத்திற்கு செல்லுங்கள்',
    // ── Navbar & Footer & Profile Extra ───────────────────────────────────────
    brandVelSiddhar: 'வேல் சித்தர்',
    brandArakkattalai: 'அறக்கட்டளை',
    address: 'புதிய எண்.19, பழைய எண்.61, 27வது தெரு, L-பிளாக், அண்ணா நகர் கிழக்கு, சென்னை - 600 102. இந்தியா',
    emailId: 'sales@velsiddhararakkattalai.com',
    phoneNum: '(044) 4859 9296',
    admin: 'நிர்வாகி (ADMIN)',
    myOrders: 'எனது ஆர்டர்கள்',
    healthNutrition: 'ஆரோக்கியம் மற்றும் ஊட்டச்சத்து',
    companyProfileTitle: 'நிறுவனத்தின் சுயவிவரம்',
    heritageAndReviews: 'மரபு மற்றும் மதிப்புரைகள்',
    coughAndCold: 'சளி மற்றும் இருமல்',
    fever: 'காய்ச்சல்',
    migraine: 'ஒற்றைத் தலைவலி',
    sinus: 'சைனஸ்',
    bodyCare: 'உடல் பராமரிப்பு',
    faceCare: 'முகப் பராமரிப்பு',
    ayurvedicHairOil: 'ஆயுர்வேத முடி எண்ணெய்',
    skinBeautyCare: 'சருமம் அழகு பராமரிப்பு',
    constipation: 'மலச்சிக்கல்',
    diabetesControl: 'சர்க்கரை நோய் / நீரிழிவு கட்டுப்பாடு',
    digestion: 'செரிமானம்',
    gastroHealth: 'இரைப்பை மற்றும் நெஞ்செரிச்சல்',
    obesity: 'உடல் பருமன்',
    pilesHemorrhoid: 'மூலம்',
    cpHeading: 'வேல் சித்தர் அறக்கட்டளை - நிறுவனத்தின் சுயவிவரம்',
    cpSubheading: 'இந்தியாவின் சிறந்த ஆன்லைன் ஆயுர்வேத கடைகளில் ஒன்று',
    cpP1: 'ஆயுர்வேத மருந்துகளை தேடுவது ஒரு நாள் முழுவதுமான வேலையாக இருக்கக்கூடாது. கடைகளில் சென்று, கேட்டு, நீங்கள் தேடுவது கிடைக்காமல் போவது ஏமாற்றமாக இருக்கலாம்.',
    cpP2: 'அதனால்தான் வேல் சித்தர் அறக்கட்டளை விஷயங்களை எளிதாக்குகிறது. வெளியே அலைந்து தேடும் நேரத்தை வீணடிப்பதற்கு பதிலாக, உங்களுக்கான தேவையை மட்டும் சொல்லுங்கள், அதை உங்கள் வீட்டுக்கே கொண்டு வந்து சேர்க்கிறோம்.',
    cpP3: 'ஆயுர்வேதம் உங்கள் ஆரோக்கியத்தை பராமரிக்க ஒரு இயற்கை வழி. இது சரியான முறையில் எடுத்துக்கொண்டால் பாதுகாப்பானது மற்றும் நீண்டகால நல்வாழ்வில் கவனம் செலுத்துகிறது. சரியான வழிகாட்டுதலுடன் சர்க்கரை நோயாளிகளும் இதை பயன்படுத்தலாம்.',
    cpP4: 'ஆயுர்வேதத்தின் மற்றொரு சிறப்பம்சம், இது முழுமையான ஆரோக்கியத்தில் கவனம் செலுத்துகிறது, எனவே ஒரே நேரத்தில் பல பிரச்சனைகளை நிர்வகிக்க உதவுகிறது. நாங்கள் இலவச மருத்துவ முகாம்கள் நடத்தி, தேவைப்படுபவர்களுக்கு மருந்துகள் வழங்கியுள்ளோம்.',
    cpP5: 'நாங்கள் நல்ல தரமான பொருட்களை வழங்குவதிலும், சரியான நேரத்தில் டெலிவரி செய்வதிலும் கவனம் செலுத்துகிறோம். கூடுதல் சிரமம் இல்லாமல் சரியான நேரத்தில் சரியான மருந்துகளை உங்களுக்கு கிடைக்கச் செய்வதே எங்கள் எளிய நோக்கம்.',
    exploreCollections: 'எங்கள் தொகுப்புகளை ஆராயுங்கள்',
  },
};

const LangContext = createContext();

export const LangProvider = ({ children }) => {
  const [lang, setLang] = useState('en');
  const t = (key) => translations[lang][key] || key;
  const toggleLang = () => setLang(prev => prev === 'en' ? 'ta' : 'en');
  return (
    <LangContext.Provider value={{ lang, t, toggleLang }}>
      {children}
    </LangContext.Provider>
  );
};

export const useLang = () => useContext(LangContext);
